# Installation and Setup

## Pandas
- **Pandas** is a data analysis library built on top of the Python programming language.
- We need to install Python to install Pandas.

## Installing Python and Pandas
- `uv` is a command-line tool for managing Python projects.
- `uv` helps download a specific version of Python and various libraries.
- `uv sync` downloads the requirements specified in the `pyproject.toml` file.
- The command will download Python, Pandas, Jupyter Lab, and more.

## Jupyter Lab
- Jupyter Lab will be our coding environment for the course.
- Jupyter Lab is a server, a continuously running program that listens to requests and issues responses.
- Jupyter Lab runs inside a web browser like Google Chrome. It opens Jupyter Notebooks.

## Intro to Jupyter Notebook
- Jupyter Notebooks have a `.ipynb` file extension. They used to be called iPython Notebooks.
- Copy-paste functionalities are available under **Edit** menu.
- The options in the **View** menu toggle the header and the toolbar.
- If serious errors (i.e., frozen execution) occur, acces the **Kernel** menu and select `Restart & Clear Output`.
- A Jupyter Notebook consists of Python cells and text cells.
- Execute a cell with `Shift + Enter` or `Ctrl + Enter`.
- Jupyter will output the last cell evaluation below the cell.

## Create, Saving, and Closing a Jupyter Notebook
- Save a Jupyter Notebook with `Command + S` (macOS) and `Control + S` (Windows). Jupyter includes an auto-save feature.
- To shut down a Notebook, save and close its tab. 
- Click the **Running Terminals and Kernels** button on the left-hand menu (the second icon from the top).
- Click **Shut Down All** in the **Kernels** section or individually target a specific Notebook you'd like to close.
- Go to **File -> Shut Down** in the main menu.

## Cell Types and Cell Modes
- Cell types: **Code** and **Markdown**. Select from the dropdown menu in the toolbar.
- Cell modes: **Edit Mode** (green outline) or **Command Mode** (blue outline).
- Double-click into a Markdown cell or single-click into a code cell to enter **Edit Mode**.
- Press the Escape key to go to **Command Mode**.
- **Command Mode** is for notebook operations - navigation, cell deletion, cell movement
- Alternatively, in command mode, press "m" to make a cell Markdown and "y" to make it a code cell

## Code Cell Execution

- We need to "execute" a cell to run the Python code inside of it.
- Press **Shift + Enter** to execute a code cell and move to the next cell.
- Press **Ctrl + Enter** to execute a code cell and stay in the same cell.
- Executing a Markdown cell will render the formatting within it.
- A cell can be executed any number of times.
- You can execute cells in any order.

- Multiple operations can take place in a single cell.
- The cell will automatically output the last expression.
- Any operation not saved to a variable will be thrown out.

## Popular Keyboard Shortcuts
- In Command Mode, press `a` to insert a cell above the currently selected one
- In Command Mode, press `b` to insert a cell below the currently selected one
- In Command Mode, press `x` to cut a cell (i.e delete it)
- Both add options are available on the main menu under **Insert**.

## Import Libraries into Jupyter Lab
- Use Python's `import` keyword to bring a library into the Jupyter Notebook.
- We can optionally assign an alias to a library with the `as` keyword.
- The common alias for Pandas is `pd`.
- Make sure to execute the `import` cell every time you launch the Notebook.

In [16]:
import pandas as pd
from IPython.display import Markdown, display

- Access the Pandas library with `pd`.
- Write a dot and press Tab to see the top-level library constructs.

In [17]:
books = pd.read_csv("library/books.csv")

books.head()

   Book ID                    Title               Author        Genre
0        1    To Kill a Mockingbird           Harper Lee      Fiction
1        2                     1984        George Orwell      Fiction
2        3  A Brief History of Time      Stephen Hawking      Science
3        4         The Great Gatsby  F. Scott Fitzgerald      Fiction
4        5             Freakonomics        Steven Levitt  Non-Fiction

In [18]:
books.shape

(35, 4)

In [19]:
info_df = pd.DataFrame(
    {
        "Column": books.columns,
        "Non-Null Count": books.notnull().sum().values,
        "Dtype": books.dtypes.values,
    }
)

display(Markdown(info_df.to_markdown(index=False)))

| Column   |   Non-Null Count | Dtype   |
|:---------|-----------------:|:--------|
| Book ID  |               35 | int64   |
| Title    |               35 | str     |
| Author   |               35 | str     |
| Genre    |               35 | str     |

In [22]:
books.describe()

         Book ID
count  35.000000
mean   18.000000
std    10.246951
min     1.000000
25%     9.500000
50%    18.000000
75%    26.500000
max    35.000000