# Series

In [1]:
import pandas as pd

## Create a Series Object from a List
- A `Series` is a single column of ordered homogenous data (data of the same type).
- A `Series` combines the the best features of a list and a dictionary.
- Pandas assigns an identifier to each value. The identifiers make up the **index** of the `Series`.
- If we do not provide a custom index, Pandas defaults to an ascending numeric index.
- The index starts counting from 0.

In [2]:
ice_cream = ["Chocolate", "Vanilla", "Strawberry", "Rum Raisin"]
pd.Series(ice_cream)

0     Chocolate
1       Vanilla
2    Strawberry
3    Rum Raisin
dtype: str

- A `Series` output includes the data type (`dtype`) of its values.
- `int64` is a 64-bit integer (whole number occupying 64-bits/8 bytes of memory)

In [3]:
lottery_numbers = [4, 8, 15, 16, 23, 42]
pd.Series(lottery_numbers)

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

- A `Series` can contain duplicates.

In [4]:
pd.Series([True, False, False, False, True])

0     True
1    False
2    False
3    False
4     True
dtype: bool

## Create a Series Object from a Dictionary
- The `Series` index does not have to be numeric. It can be a variety of data types.
- If we pass a dictionary to the `Series` constructor, Pandas will use the keys as the index labels.
- Pandas will keep track of each element's order (even if the index is non-numeric).

In [5]:
sushi = {"Salmon": "Orange", "Tuna": "Red", "Eel": "Brown"}
pd.Series(sushi)

Salmon    Orange
Tuna         Red
Eel        Brown
dtype: str

## Intro to Series Methods
- A method is a function attached to an object. It is a command we can issue to the object.
- Invoke a method with the `object.method()` syntax.
- A variable is a name for an existing object. Use `variable.method()` in that case.

In [6]:
prices = pd.Series([2.99, 4.45, 1.36])
prices

0    2.99
1    4.45
2    1.36
dtype: float64

- The `sum` method adds together the `Series`' values.
- The methods return a `NumPy` scalar value of type `numpy.float64`.
- NumPy is a dependency of Pandas. The `Series` object relies on NumPy's `ndarray` object under the hood.
- JupyterLab prints out the string representation of the NumPy numeric object (`np.float64`)

In [7]:
prices.sum()

np.float64(8.8)

- Pass a NumPy object into Python's `print` function to see its user-friendly string representation.

In [8]:
print(prices.sum())

8.8

- The `product` method multiplies the `Series`' values.
- The `mean` method calculates the average of the `Series`' values.
- The `std` method calculates the standard deviation of the `Series`' values.

In [9]:
prices.product()

np.float64(18.095480000000006)

In [10]:
prices.mean()

np.float64(2.9333333333333336)

In [11]:
prices.std()

1.5457791994115246

## Intro to Series Attributes
- An **attribute** is a piece of data that lives on an object.
- An **attribute** is a fact, a detail, a characteristic of the object.
- Access an attribute with `object.attribute` syntax.

In [12]:
adjectives = pd.Series(
    ["Smart", "Handsome", "Charming", "Brilliant", "Humble", "Smart"]
)
adjectives

0        Smart
1     Handsome
2     Charming
3    Brilliant
4       Humble
5        Smart
dtype: str

- The `size` attribute returns a count of the number of values in the `Series`.

In [13]:
adjectives.size

6

- The `is_unique` attribute returns `True` if the `Series` has no duplicate values.

In [14]:
adjectives.is_unique

False

- The `index`return the underlying object that hold the `Series`' index labels.
- You can think of a `Series` object as an collection of other objects.
- Some developers use the word "composition" to define this design. An object is composed of other objects.

In [15]:
adjectives.index

RangeIndex(start=0, stop=6, step=1)

- Python's `type` function returns the class of a specified value.
- The class is the blueprint that an object is made from.
- The output can reveal the library that defines the class.
- The `RangeIndex` object/class comes from the Pandas library.

In [16]:
type(adjectives)

pandas.Series

In [17]:
type(adjectives.index)

pandas.RangeIndex

- The `values` attribute returns the object storing the `Series`'s values.

In [18]:
adjectives.values

<ArrowStringArray>
['Smart', 'Handsome', 'Charming', 'Brilliant', 'Humble', 'Smart']
Length: 6, dtype: str

In [19]:
type(adjectives.values)

pandas.arrays.ArrowStringArray

## Parameters and Arguments
- A **parameter** is the name for an expected input to a function/method/class instantiation.
- An **argument** is the concrete value we provide for a parameter during invocation.
- We can pass arguments either sequentially (based on parameter order) or with explicit parameter names written out.

In [20]:
fruits = ["Apple", "Orange", "Plum", "Grape", "Blueberry", "Watermelon"]
weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Monday"]

- The first parameter for the `Series` constructor is `data`, which represents the values of the `Series`.
- The constructor will provide fallback/default values to the other parameters.
- Use Shift + Tab to see the `Series` documentation and the default values.
- The `Series` values can contain duplicates.

In [21]:
pd.Series(fruits)
pd.Series(data=fruits)

0         Apple
1        Orange
2          Plum
3         Grape
4     Blueberry
5    Watermelon
dtype: str

- The second parameter for the `Series` constructor is `index`, which holds the index labels.
- Notice that the `Series` index _can_ contain duplicates (although this is not ideal).

In [22]:
pd.Series(fruits, weekdays)
pd.Series(data=fruits, index=weekdays)

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday          Grape
Friday        Blueberry
Monday       Watermelon
dtype: str

- Reversing the order of arguments results in a different `Series`.
- `weekdays` becomes the argument for `data`, and `fruits` becomes the argument for `index`.

In [23]:
pd.Series(weekdays, fruits)

Apple            Monday
Orange          Tuesday
Plum          Wednesday
Grape          Thursday
Blueberry        Friday
Watermelon       Monday
dtype: str

- If using keyword arguments, the order does not matter.
- Python matches the parameter to the argument by its name, not by its order.
- Keyword arguments also provide context on what the parameter represents.

In [24]:
pd.Series(data=fruits, index=weekdays)
pd.Series(index=weekdays, data=fruits)

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday          Grape
Friday        Blueberry
Monday       Watermelon
dtype: str

- You can mix-and-match positional arguments with keyword arguments.
- Use keyword arguments to skip required arguments.
- The `name` parameter assigns a name to the `Series`.

In [25]:
pd.Series(fruits, index=weekdays, name="Diet")

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday          Grape
Friday        Blueberry
Monday       Watermelon
Name: Diet, dtype: str

- A `Series` can be empty. Pandas will assume an `object` data type.

In [26]:
pd.Series()

Series([], dtype: object)

## Import Series with the pd.read_csv Function

### The CSV Format
- A comma-separated values (**CSV**) is a plain text file that uses line breaks to separate rows and commas to separate row values.
- The comma-separated values (CSV) format stores one record per row.
- The CSV format separates each row's values with commas.

```
name,strength,magic,speed
Zorblax,9,2,5
Mira,4,9,8
Thud,10,1,2
Eloria,3,10,7
Sorel,2,,4
```

- Pandas ships with many functions for importing different types of files. Their names begin with `read`.
- The `read_csv` function imports a CSV text file.
- The function accepts 30+ parameters. The first one specifies the file name/path.
- The `read_csv` function imports the dataset as a `DataFrame`, a 2-dimensional table.

In [27]:
pd.read_csv("pokemon.csv")

              Name              Type
0        Bulbasaur     Grass, Poison
1          Ivysaur     Grass, Poison
2         Venusaur     Grass, Poison
3       Charmander              Fire
4       Charmeleon              Fire
...            ...               ...
1005  Iron Valiant   Fairy, Fighting
1006      Koraidon  Fighting, Dragon
1007      Miraidon  Electric, Dragon
1008  Walking Wake     Water, Dragon
1009   Iron Leaves    Grass, Psychic

[1010 rows x 2 columns]

- The `usecols` parameter accepts a list of the column(s) to import.
- Pandas still imports the dataset as a 1-column `DataFrame`.

In [28]:
pd.read_csv("pokemon.csv", usecols=["Name"])

              Name
0        Bulbasaur
1          Ivysaur
2         Venusaur
3       Charmander
4       Charmeleon
...            ...
1005  Iron Valiant
1006      Koraidon
1007      Miraidon
1008  Walking Wake
1009   Iron Leaves

[1010 rows x 1 columns]

- The `squeeze` method converts a 1-column `DataFrame` to a `Series`.
- Pass an argument of `columns` to specify the orientation/direction of the compression (squeeze).
- Let's assign the `DataFrame` to a variable like `pokemon`. This will be our import code at the start of each lesson.

In [29]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
pokemon

0          Bulbasaur
1            Ivysaur
2           Venusaur
3         Charmander
4         Charmeleon
            ...
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, Length: 1010, dtype: str

In [30]:
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")
google

0         2.492181
1         2.690134
2         2.717208
3         2.604694
4         2.632761
           ...
5392    333.260010
5393    334.549988
5394    336.010010
5395    338.250000
5396    338.000000
Name: Price, Length: 5397, dtype: float64

## The head and tail Methods
- The `head` method returns a number of rows from the top/beginning of the `Series`.
- The `tail` method returns a number of rows from the bottom/end of the `Series`.

In [31]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

In [32]:
pokemon.head()
pokemon.head(7)
pokemon.head(n=7)
pokemon.head(1)

0    Bulbasaur
Name: Name, dtype: str

In [33]:
google.tail()
google.tail(5)
google.tail(n=5)

google.tail(2)

5395    338.25
5396    338.00
Name: Price, dtype: float64

## Passing Series to Python's Built-In Functions
- Python's functions support Pandas objects as arguments.

In [34]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

- The `len` function returns the length of the `Series`.

In [35]:
pokemon.size
len(pokemon)

1010

- The `type` function returns the type of an object.
- `type` can help identify the library that an object is coming from.

In [36]:
type(pokemon)

pandas.Series

- The `list` function converts the `Series` to a list.

In [37]:
list(pokemon)

['Bulbasaur',
 'Ivysaur',
 'Venusaur',
 'Charmander',
 'Charmeleon',
 'Charizard',
 'Squirtle',
 'Wartortle',
 'Blastoise',
 'Caterpie',
 'Metapod',
 'Butterfree',
 'Weedle',
 'Kakuna',
 'Beedrill',
 'Pidgey',
 'Pidgeotto',
 'Pidgeot',
 'Rattata',
 'Raticate',
 'Spearow',
 'Fearow',
 'Ekans',
 'Arbok',
 'Pikachu',
 'Raichu',
 'Sandshrew',
 'Sandslash',
 'Nidoran♀',
 'Nidorina',
 'Nidoqueen',
 'Nidoran♂',
 'Nidorino',
 'Nidoking',
 'Clefairy',
 'Clefable',
 'Vulpix',
 'Ninetales',
 'Jigglypuff',
 'Wigglytuff',
 'Zubat',
 'Golbat',
 'Oddish',
 'Gloom',
 'Vileplume',
 'Paras',
 'Parasect',
 'Venonat',
 'Venomoth',
 'Diglett',
 'Dugtrio',
 'Meowth',
 'Persian',
 'Psyduck',
 'Golduck',
 'Mankey',
 'Primeape',
 'Growlithe',
 'Arcanine',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Abra',
 'Kadabra',
 'Alakazam',
 'Machop',
 'Machoke',
 'Machamp',
 'Bellsprout',
 'Weepinbell',
 'Victreebel',
 'Tentacool',
 'Tentacruel',
 'Geodude',
 'Graveler',
 'Golem',
 'Ponyta',
 'Rapidash',
 'Slowpoke',
 'Slowbro',
 'Magnemite',
 'Magneton',
 'Farfetch’d',
 'Doduo',
 'Dodrio',
 'Seel',
 'Dewgong',
 'Grimer',
 'Muk',
 'Shellder',
 'Cloyster',
 'Gastly',
 'Haunter',
 'Gengar',
 'Onix',
 'Drowzee',
 'Hypno',
 'Krabby',
 'Kingler',
 'Voltorb',
 'Electrode',
 'Exeggcute',
 'Exeggutor',
 'Cubone',
 'Marowak',
 'Hitmonlee',
 'Hitmonchan',
 'Lickitung',
 'Koffing',
 'Weezing',
 'Rhyhorn',
 'Rhydon',
 'Chansey',
 'Tangela',
 'Kangaskhan',
 'Horsea',
 'Seadra',
 'Goldeen',
 'Seaking',
 'Staryu',
 'Starmie',
 'Mr. Mime',
 'Scyther',
 'Jynx',
 'Electabuzz',
 'Magmar',
 'Pinsir',
 'Tauros',
 'Magikarp',
 'Gyarados',
 'Lapras',
 'Ditto',
 'Eevee',
 'Vaporeon',
 'Jolteon',
 'Flareon',
 'Porygon',
 'Omanyte',
 'Omastar',
 'Kabuto',
 'Kabutops',
 'Aerodactyl',
 'Snorlax',
 'Articuno',
 'Zapdos',
 'Moltres',
 'Dratini',
 'Dragonair',
 'Dragonite',
 'Mewtwo',
 'Mew',
 'Chikorita',
 'Bayleef',
 'Meganium',
 'Cyndaquil',
 'Quilava',
 'Typhlosion',
 'Totodile',
 'Croconaw',
 'Feraligatr',
 'Sentret',
 'Furret',
 'Hoothoot',
 'Noctowl',
 'Ledyba',
 'Ledian',
 'Spinarak',
 'Ariados',
 'Crobat',
 'Chinchou',
 'Lanturn',
 'Pichu',
 'Cleffa',
 'Igglybuff',
 'Togepi',
 'Togetic',
 'Natu',
 'Xatu',
 'Mareep',
 'Flaaffy',
 'Ampharos',
 'Bellossom',
 'Marill',
 'Azumarill',
 'Sudowoodo',
 'Politoed',
 'Hoppip',
 'Skiploom',
 'Jumpluff',
 'Aipom',
 'Sunkern',
 'Sunflora',
 'Yanma',
 'Wooper',
 'Quagsire',
 'Espeon',
 'Umbreon',
 'Murkrow',
 'Slowking',
 'Misdreavus',
 'Unown',
 'Wobbuffet',
 'Girafarig',
 'Pineco',
 'Forretress',
 'Dunsparce',
 'Gligar',
 'Steelix',
 'Snubbull',
 'Granbull',
 'Qwilfish',
 'Scizor',
 'Shuckle',
 'Heracross',
 'Sneasel',
 'Teddiursa',
 'Ursaring',
 'Slugma',
 'Magcargo',
 'Swinub',
 'Piloswine',
 'Corsola',
 'Remoraid',
 'Octillery',
 'Delibird',
 'Mantine',
 'Skarmory',
 'Houndour',
 'Houndoom',
 'Kingdra',
 'Phanpy',
 'Donphan',
 'Porygon2',
 'Stantler',
 'Smeargle',
 'Tyrogue',
 'Hitmontop',
 'Smoochum',
 'Elekid',
 'Magby',
 'Miltank',
 'Blissey',
 'Raikou',
 'Entei',
 'Suicune',
 'Larvitar',
 'Pupitar',
 'Tyranitar',
 'Lugia',
 'Ho-Oh',
 'Celebi',
 'Treecko',
 'Grovyle',
 'Sceptile',
 'Torchic',
 'Combusken',
 'Blaziken',
 'Mudkip',
 'Marshtomp',
 'Swampert',
 'Poochyena',
 'Mightyena',
 'Zigzagoon',
 'Linoone',
 'Wurmple',
 'Silcoon',
 'Beautifly',
 'Cascoon',
 'Dustox',
 'Lotad',
 'Lombre',
 'Ludicolo',
 'Seedot',
 'Nuzleaf',
 'Shiftry',
 'Taillow',
 'Swellow',
 'Wingull',
 'Pelipper',
 'Ralts',
 'Kirlia',
 'Gardevoir',
 'Surskit',
 'Masquerain',
 'Shroomish',
 'Breloom',
 'Slakoth',
 'Vigoroth',
 'Slaking',
 'Nincada',
 'Ninjask',
 'Shedinja',
 'Whismur',
 'Loudred',
 'Exploud',
 'Makuhita',
 'Hariyama',
 'Azurill',
 'Nosepass',
 'Skitty',
 'Delcatty',
 'Sableye',
 'Mawile',
 'Aron',
 'Lairon',
 'Aggron',
 'Meditite',
 'Medicham',
 'Electrike',
 'Manectric',
 'Plusle',
 'Minun',
 'Volbeat',
 'Illumise',
 'Roselia',
 'Gulpin',
 'Swalot',
 'Carvanha',
 'Sharpedo',
 'Wailmer',
 'Wailord',
 'Numel',
 'Camerupt',
 'Torkoal',
 'Spoink',
 'Grumpig',
 'Spinda',
 'Trapinch',
 'Vibrava',
 'Flygon',
 'Cacnea',
 'Cacturne',
 'Swablu',
 'Altaria',
 'Zangoose',
 'Seviper',
 'Lunatone',
 'Solrock',
 'Barboach',
 'Whiscash',
 'Corphish',
 'Crawdaunt',
 'Baltoy',
 'Claydol',
 'Lileep',
 'Cradily',
 'Anorith',
 'Armaldo',
 'Feebas',
 'Milotic',
 'Castform',
 'Kecleon',
 'Shuppet',
 'Banette',
 'Duskull',
 'Dusclops',
 'Tropius',
 'Chimecho',
 'Absol',
 'Wynaut',
 'Snorunt',
 'Glalie',
 'Spheal',
 'Sealeo',
 'Walrein',
 'Clamperl',
 'Huntail',
 'Gorebyss',
 'Relicanth',
 'Luvdisc',
 'Bagon',
 'Shelgon',
 'Salamence',
 'Beldum',
 'Metang',
 'Metagross',
 'Regirock',
 'Regice',
 'Registeel',
 'Latias',
 'Latios',
 'Kyogre',
 'Groudon',
 'Rayquaza',
 'Jirachi',
 'Deoxys',
 'Turtwig',
 'Grotle',
 'Torterra',
 'Chimchar',
 'Monferno',
 'Infernape',
 'Piplup',
 'Prinplup',
 'Empoleon',
 'Starly',
 'Staravia',
 'Staraptor',
 'Bidoof',
 'Bibarel',
 'Kricketot',
 'Kricketune',
 'Shinx',
 'Luxio',
 'Luxray',
 'Budew',
 'Roserade',
 'Cranidos',
 'Rampardos',
 'Shieldon',
 'Bastiodon',
 'Burmy',
 'Wormadam',
 'Mothim',
 'Combee',
 'Vespiquen',
 'Pachirisu',
 'Buizel',
 'Floatzel',
 'Cherubi',
 'Cherrim',
 'Shellos',
 'Gastrodon',
 'Ambipom',
 'Drifloon',
 'Drifblim',
 'Buneary',
 'Lopunny',
 'Mismagius',
 'Honchkrow',
 'Glameow',
 'Purugly',
 'Chingling',
 'Stunky',
 'Skuntank',
 'Bronzor',
 'Bronzong',
 'Bonsly',
 'Mime Jr.',
 'Happiny',
 'Chatot',
 'Spiritomb',
 'Gible',
 'Gabite',
 'Garchomp',
 'Munchlax',
 'Riolu',
 'Lucario',
 'Hippopotas',
 'Hippowdon',
 'Skorupi',
 'Drapion',
 'Croagunk',
 'Toxicroak',
 'Carnivine',
 'Finneon',
 'Lumineon',
 'Mantyke',
 'Snover',
 'Abomasnow',
 'Weavile',
 'Magnezone',
 'Lickilicky',
 'Rhyperior',
 'Tangrowth',
 'Electivire',
 'Magmortar',
 'Togekiss',
 'Yanmega',
 'Leafeon',
 'Glaceon',
 'Gliscor',
 'Mamoswine',
 'Porygon-Z',
 'Gallade',
 'Probopass',
 'Dusknoir',
 'Froslass',
 'Rotom',
 'Uxie',
 'Mesprit',
 'Azelf',
 'Dialga',
 'Palkia',
 'Heatran',
 'Regigigas',
 'Giratina',
 'Cresselia',
 'Phione',
 'Manaphy',
 'Darkrai',
 'Shaymin',
 'Arceus',
 'Victini',
 'Snivy',
 'Servine',
 'Serperior',
 'Tepig',
 'Pignite',
 'Emboar',
 'Oshawott',
 'Dewott',
 'Samurott',
 'Patrat',
 'Watchog',
 'Lillipup',
 'Herdier',
 'Stoutland',
 'Purrloin',
 'Liepard',
 'Pansage',
 'Simisage',
 'Pansear',
 'Simisear',
 'Panpour',
 'Simipour',
 'Munna',
 'Musharna',
 'Pidove',
 'Tranquill',
 'Unfezant',
 'Blitzle',
 'Zebstrika',
 'Roggenrola',
 'Boldore',
 'Gigalith',
 'Woobat',
 'Swoobat',
 'Drilbur',
 'Excadrill',
 'Audino',
 'Timburr',
 'Gurdurr',
 'Conkeldurr',
 'Tympole',
 'Palpitoad',
 'Seismitoad',
 'Throh',
 'Sawk',
 'Sewaddle',
 'Swadloon',
 'Leavanny',
 'Venipede',
 'Whirlipede',
 'Scolipede',
 'Cottonee',
 'Whimsicott',
 'Petilil',
 'Lilligant',
 'Basculin',
 'Sandile',
 'Krokorok',
 'Krookodile',
 'Darumaka',
 'Darmanitan',
 'Maractus',
 'Dwebble',
 'Crustle',
 'Scraggy',
 'Scrafty',
 'Sigilyph',
 'Yamask',
 'Cofagrigus',
 'Tirtouga',
 'Carracosta',
 'Archen',
 'Archeops',
 'Trubbish',
 'Garbodor',
 'Zorua',
 'Zoroark',
 'Minccino',
 'Cinccino',
 'Gothita',
 'Gothorita',
 'Gothitelle',
 'Solosis',
 'Duosion',
 'Reuniclus',
 'Ducklett',
 'Swanna',
 'Vanillite',
 'Vanillish',
 'Vanilluxe',
 'Deerling',
 'Sawsbuck',
 'Emolga',
 'Karrablast',
 'Escavalier',
 'Foongus',
 'Amoonguss',
 'Frillish',
 'Jellicent',
 'Alomomola',
 'Joltik',
 'Galvantula',
 'Ferroseed',
 'Ferrothorn',
 'Klink',
 'Klang',
 'Klinklang',
 'Tynamo',
 'Eelektrik',
 'Eelektross',
 'Elgyem',
 'Beheeyem',
 'Litwick',
 'Lampent',
 'Chandelure',
 'Axew',
 'Fraxure',
 'Haxorus',
 'Cubchoo',
 'Beartic',
 'Cryogonal',
 'Shelmet',
 'Accelgor',
 'Stunfisk',
 'Mienfoo',
 'Mienshao',
 'Druddigon',
 'Golett',
 'Golurk',
 'Pawniard',
 'Bisharp',
 'Bouffalant',
 'Rufflet',
 'Braviary',
 'Vullaby',
 'Mandibuzz',
 'Heatmor',
 'Durant',
 'Deino',
 'Zweilous',
 'Hydreigon',
 'Larvesta',
 'Volcarona',
 'Cobalion',
 'Terrakion',
 'Virizion',
 'Tornadus',
 'Thundurus',
 'Reshiram',
 'Zekrom',
 'Landorus',
 'Kyurem',
 'Keldeo',
 'Meloetta',
 'Genesect',
 'Chespin',
 'Quilladin',
 'Chesnaught',
 'Fennekin',
 'Braixen',
 'Delphox',
 'Froakie',
 'Frogadier',
 'Greninja',
 'Bunnelby',
 'Diggersby',
 'Fletchling',
 'Fletchinder',
 'Talonflame',
 'Scatterbug',
 'Spewpa',
 'Vivillon',
 'Litleo',
 'Pyroar',
 'Flabébé',
 'Floette',
 'Florges',
 'Skiddo',
 'Gogoat',
 'Pancham',
 'Pangoro',
 'Furfrou',
 'Espurr',
 'Meowstic',
 'Honedge',
 'Doublade',
 'Aegislash',
 'Spritzee',
 'Aromatisse',
 'Swirlix',
 'Slurpuff',
 'Inkay',
 'Malamar',
 'Binacle',
 'Barbaracle',
 'Skrelp',
 'Dragalge',
 'Clauncher',
 'Clawitzer',
 'Helioptile',
 'Heliolisk',
 'Tyrunt',
 'Tyrantrum',
 'Amaura',
 'Aurorus',
 'Sylveon',
 'Hawlucha',
 'Dedenne',
 'Carbink',
 'Goomy',
 'Sliggoo',
 'Goodra',
 'Klefki',
 'Phantump',
 'Trevenant',
 'Pumpkaboo',
 'Gourgeist',
 'Bergmite',
 'Avalugg',
 'Noibat',
 'Noivern',
 'Xerneas',
 'Yveltal',
 'Zygarde',
 'Diancie',
 'Hoopa',
 'Volcanion',
 'Rowlet',
 'Dartrix',
 'Decidueye',
 'Litten',
 'Torracat',
 'Incineroar',
 'Popplio',
 'Brionne',
 'Primarina',
 'Pikipek',
 'Trumbeak',
 'Toucannon',
 'Yungoos',
 'Gumshoos',
 'Grubbin',
 'Charjabug',
 'Vikavolt',
 'Crabrawler',
 'Crabominable',
 'Oricorio',
 'Cutiefly',
 'Ribombee',
 'Rockruff',
 'Lycanroc',
 'Wishiwashi',
 'Mareanie',
 'Toxapex',
 'Mudbray',
 'Mudsdale',
 'Dewpider',
 'Araquanid',
 'Fomantis',
 'Lurantis',
 'Morelull',
 'Shiinotic',
 'Salandit',
 'Salazzle',
 'Stufful',
 'Bewear',
 'Bounsweet',
 'Steenee',
 'Tsareena',
 'Comfey',
 'Oranguru',
 'Passimian',
 'Wimpod',
 'Golisopod',
 'Sandygast',
 'Palossand',
 'Pyukumuku',
 'Type: Null',
 'Silvally',
 'Minior',
 'Komala',
 'Turtonator',
 'Togedemaru',
 'Mimikyu',
 'Bruxish',
 'Drampa',
 'Dhelmise',
 'Jangmo-o',
 'Hakamo-o',
 'Kommo-o',
 'Tapu Koko',
 'Tapu Lele',
 'Tapu Bulu',
 'Tapu Fini',
 'Cosmog',
 'Cosmoem',
 'Solgaleo',
 'Lunala',
 'Nihilego',
 'Buzzwole',
 'Pheromosa',
 'Xurkitree',
 'Celesteela',
 'Kartana',
 'Guzzlord',
 'Necrozma',
 'Magearna',
 'Marshadow',
 'Poipole',
 'Naganadel',
 'Stakataka',
 'Blacephalon',
 'Zeraora',
 'Meltan',
 'Melmetal',
 'Grookey',
 'Thwackey',
 'Rillaboom',
 'Scorbunny',
 'Raboot',
 'Cinderace',
 'Sobble',
 'Drizzile',
 'Inteleon',
 'Skwovet',
 'Greedent',
 'Rookidee',
 'Corvisquire',
 'Corviknight',
 'Blipbug',
 'Dottler',
 'Orbeetle',
 'Nickit',
 'Thievul',
 'Gossifleur',
 'Eldegoss',
 'Wooloo',
 'Dubwool',
 'Chewtle',
 'Drednaw',
 'Yamper',
 'Boltund',
 'Rolycoly',
 'Carkol',
 'Coalossal',
 'Applin',
 'Flapple',
 'Appletun',
 'Silicobra',
 'Sandaconda',
 'Cramorant',
 'Arrokuda',
 'Barraskewda',
 'Toxel',
 'Toxtricity',
 'Sizzlipede',
 'Centiskorch',
 'Clobbopus',
 'Grapploct',
 'Sinistea',
 'Polteageist',
 'Hatenna',
 'Hattrem',
 'Hatterene',
 'Impidimp',
 'Morgrem',
 'Grimmsnarl',
 'Obstagoon',
 'Perrserker',
 'Cursola',
 'Sirfetch’d',
 'Mr. Rime',
 'Runerigus',
 'Milcery',
 'Alcremie',
 'Falinks',
 'Pincurchin',
 'Snom',
 'Frosmoth',
 'Stonjourner',
 'Eiscue',
 'Indeedee',
 'Morpeko',
 'Cufant',
 'Copperajah',
 'Dracozolt',
 'Arctozolt',
 'Dracovish',
 'Arctovish',
 'Duraludon',
 'Dreepy',
 'Drakloak',
 'Dragapult',
 'Zacian',
 'Zamazenta',
 'Eternatus',
 'Kubfu',
 'Urshifu',
 'Zarude',
 'Regieleki',
 'Regidrago',
 'Glastrier',
 'Spectrier',
 'Calyrex',
 'Wyrdeer',
 'Kleavor',
 'Ursaluna',
 'Basculegion',
 'Sneasler',
 'Overqwil',
 'Enamorus',
 'Sprigatito',
 'Floragato',
 'Meowscarada',
 'Fuecoco',
 'Crocalor',
 'Skeledirge',
 'Quaxly',
 'Quaxwell',
 'Quaquaval',
 'Lechonk',
 'Oinkologne',
 'Tarountula',
 'Spidops',
 'Nymble',
 'Lokix',
 'Pawmi',
 'Pawmo',
 'Pawmot',
 'Tandemaus',
 'Maushold',
 'Fidough',
 'Dachsbun',
 'Smoliv',
 'Dolliv',
 'Arboliva',
 'Squawkabilly',
 'Nacli',
 'Naclstack',
 'Garganacl',
 'Charcadet',
 'Armarouge',
 'Ceruledge',
 'Tadbulb',
 'Bellibolt',
 'Wattrel',
 'Kilowattrel',
 'Maschiff',
 'Mabosstiff',
 'Shroodle',
 'Grafaiai',
 'Bramblin',
 'Brambleghast',
 'Toedscool',
 'Toedscruel',
 'Klawf',
 'Capsakid',
 'Scovillain',
 'Rellor',
 'Rabsca',
 'Flittle',
 'Espathra',
 'Tinkatink',
 'Tinkatuff',
 'Tinkaton',
 'Wiglett',
 'Wugtrio',
 'Bombirdier',
 'Finizen',
 'Palafin',
 'Varoom',
 'Revavroom',
 'Cyclizar',
 'Orthworm',
 'Glimmet',
 'Glimmora',
 'Greavard',
 'Houndstone',
 'Flamigo',
 'Cetoddle',
 'Cetitan',
 'Veluza',
 'Dondozo',
 'Tatsugiri',
 'Annihilape',
 'Clodsire',
 'Farigiraf',
 'Dudunsparce',
 'Kingambit',
 'Great Tusk',
 'Scream Tail',
 'Brute Bonnet',
 'Flutter Mane',
 'Slither Wing',
 'Sandy Shocks',
 'Iron Treads',
 'Iron Bundle',
 'Iron Hands',
 'Iron Jugulis',
 'Iron Moth',
 'Iron Thorns',
 'Frigibax',
 'Arctibax',
 'Baxcalibur',
 'Gimmighoul',
 'Gholdengo',
 ...]

- The `sorted` function converts the `Series` to a sorted list.

In [38]:
sorted(pokemon)
sorted(google)

[2.483985,
 2.489945,
 2.492181,
 2.52124,
 2.522979,
 2.533659,
 2.540862,
 2.54111,
 2.5426,
 2.604694,
 2.616119,
 2.632761,
 2.636486,
 2.670016,
 2.680199,
 2.690134,
 2.717208,
 2.769117,
 2.781785,
 2.830714,
 2.918142,
 2.926835,
 2.937266,
 2.940246,
 2.964587,
 2.976261,
 3.00085,
 3.150868,
 3.218922,
 3.255681,
 3.292937,
 3.354534,
 3.359502,
 3.404705,
 3.412653,
 3.42085,
 3.436746,
 3.448668,
 3.489401,
 3.499584,
 3.526906,
 3.579312,
 3.674439,
 3.704741,
 3.710205,
 4.100648,
 4.160755,
 4.161252,
 4.1692,
 4.190063,
 4.206208,
 4.207449,
 4.221855,
 4.233529,
 4.257869,
 4.263333,
 4.282706,
 4.284445,
 4.285439,
 4.285686,
 4.307543,
 4.340577,
 4.34629,
 4.36144,
 4.378579,
 4.383049,
 4.399194,
 4.416082,
 4.435953,
 4.436201,
 4.438188,
 4.445391,
 4.452098,
 4.45309,
 4.455574,
 4.455822,
 4.460045,
 4.465261,
 4.469731,
 4.470229,
 4.471719,
 4.471719,
 4.472712,
 4.48066,
 4.481903,
 4.483392,
 4.488608,
 4.492582,
 4.496804,
 4.504255,
 4.505993,
 4.515433,
 4.519903,
 4.520401,
 4.545734,
 4.563865,
 4.58746,
 4.591682,
 4.594912,
 4.595408,
 4.599382,
 4.599879,
 4.602115,
 4.61652,
 4.617266,
 4.619004,
 4.621239,
 4.6272,
 4.643841,
 4.644836,
 4.654522,
 4.654522,
 4.66694,
 4.668927,
 4.669175,
 4.671411,
 4.676378,
 4.683084,
 4.683581,
 4.689543,
 4.691529,
 4.699725,
 4.700222,
 4.727543,
 4.734995,
 4.753126,
 4.753871,
 4.755113,
 4.758342,
 4.760578,
 4.766289,
 4.766539,
 4.770016,
 4.78765,
 4.788395,
 4.791126,
 4.791872,
 4.793362,
 4.799324,
 4.801062,
 4.806279,
 4.807023,
 4.812487,
 4.814723,
 4.816462,
 4.817207,
 4.817454,
 4.830867,
 4.840057,
 4.844776,
 4.848999,
 4.851481,
 4.852724,
 4.858684,
 4.868868,
 4.868868,
 4.900411,
 4.907862,
 4.915313,
 4.916556,
 4.920281,
 4.927981,
 4.933693,
 4.966727,
 5.034781,
 5.064338,
 5.072286,
 5.075762,
 5.115503,
 5.237206,
 5.360151,
 5.433173,
 5.45056,
 5.458755,
 5.46422,
 5.521097,
 5.551895,
 5.61374,
 5.617962,
 5.637584,
 5.657952,
 5.663415,
 5.675337,
 5.680801,
 5.693717,
 5.738672,
 5.744633,
 5.790334,
 5.940103,
 5.940599,
 6.000954,
 6.344704,
 6.358364,
 6.394129,
 6.437843,
 6.446785,
 6.477832,
 6.518068,
 6.60649,
 6.606738,
 6.805685,
 6.81388,
 6.825306,
 6.833007,
 6.886656,
 6.890878,
 6.91348,
 6.940303,
 6.943532,
 6.944029,
 6.954213,
 6.954461,
 6.958931,
 6.960919,
 6.961913,
 7.005377,
 7.016555,
 7.018293,
 7.01879,
 7.022764,
 7.022764,
 7.04338,
 7.053562,
 7.053811,
 7.055053,
 7.081132,
 7.094791,
 7.095537,
 7.103485,
 7.109694,
 7.111185,
 7.120872,
 7.131054,
 7.135029,
 7.147199,
 7.149185,
 7.150677,
 7.15316,
 7.164336,
 7.164336,
 7.185448,
 7.195632,
 7.19588,
 7.22494,
 7.226182,
 7.227672,
 7.233882,
 7.233882,
 7.240587,
 7.241829,
 7.242824,
 7.247046,
 7.254745,
 7.261202,
 7.270392,
 7.276352,
 7.280326,
 7.28604,
 7.289765,
 7.30591,
 7.323792,
 7.336708,
 7.340434,
 7.344656,
 7.348134,
 7.354095,
 7.355336,
 7.357572,
 7.374959,
 7.379428,
 7.382906,
 7.384148,
 7.387128,
 7.387128,
 7.387623,
 7.394828,
 7.40203,
 7.422894,
 7.426122,
 7.428606,
 7.431089,
 7.439783,
 7.443012,
 7.454189,
 7.456176,
 7.456673,
 7.46015,
 7.473314,
 7.475301,
 7.475301,
 7.480765,
 7.500883,
 7.503615,
 7.510818,
 7.516282,
 7.524478,
 7.525721,
 7.527707,
 7.528452,
 7.530688,
 7.532674,
 7.545341,
 7.553041,
 7.575396,
 7.591292,
 7.599487,
 7.600232,
 7.602716,
 7.612651,
 7.641215,
 7.647671,
 7.65413,
 7.664064,
 7.667293,
 7.670274,
 7.690144,
 7.693124,
 7.697099,
 7.700078,
 7.703804,
 7.706537,
 7.715726,
 7.716224,
 7.717216,
 7.724419,
 7.733609,
 7.735844,
 7.741309,
 7.746772,
 7.749257,
 7.751244,
 7.766395,
 7.767885,
 7.773846,
 7.797441,
 7.797441,
 7.805885,
 7.80688,
 7.825508,
 7.82973,
 7.832711,
 7.842646,
 7.86003,
 7.896046,
 7.91517,
 7.917654,
 7.921131,
 7.940255,
 7.980742,
 7.997879,
 8.03563,
 8.044075,
 8.057736,
 8.064692,
 8.076861,
 8.079097,
 8.084064,
 8.125791,
 8.147898,
 8.170997,
 8.183661,
 8.194839,
 8.197819,
 8.200302,
 8.224645,
 8.226631,
 8.233088,
 8.246003,
 8.273324,
 8.29717,
 8.328961,
 8.371681,
 8.37466,
 8.382609,
 8.39478,
 8.397759,
 8.408192,
 8.414153,
 8.424088,
 8.427069,
 8.439487,
 8.44222,
 8.442717,
 8.450168,
 8.45588,
 8.45886,
 8.485436,
 8.491645,
 8.500339,
 8.503816,
 8.510275,
 8.51077,
 8.511515,
 8.519215,
 8.519215,
 8.527164,
 8.527164,
 8.545791,
 8.556471,
 8.580066,
 8.586274,
 8.593975,
 8.604903,
 8.605898,
 8.616327,
 8.622786,
 8.63595,
 8.64489,
 8.648119,
 8.658304,
 8.659546,
 8.660043,
 8.721887,
 8.750699,
 8.768085,
 8.769078,
 8.770321,
 8.774793,
 8.785473,
 8.789446,
 8.794661,
 8.828192,
 8.833903,
 8.883827,
 8.891775,
 8.892768,
 8.895997,
 8.904442,
 8.907919,
 8.910898,
 8.925555,
 8.93375,
 8.991126,
 9.003544,
 9.006274,
 9.006523,
 9.008759,
 9.009752,
 9.017202,
 9.051976,
 9.060672,
 9.077806,
 9.085506,
 9.1019,
 9.105129,
 9.113822,
 9.121025,
 9.138163,
 9.142632,
 9.14611,
 9.152567,
 9.158776,
 9.158776,
 9.162751,
 9.166974,
 9.175667,
 9.182125,
 9.18436,
 9.19032,
 9.21342,
 9.214413,
 9.219877,
 9.221617,
 9.222113,
 9.235027,
 9.238008,
 9.242975,
 9.251916,
 9.25291,
 9.270793,
 9.275014,
 9.282467,
 9.285449,
 9.2924,
 9.29414,
 9.300101,
 9.301592,
 9.323697,
 9.326678,
 9.328416,
 9.343815,
 9.350026,
 9.362195,
 9.368652,
 9.371136,
 9.373619,
 9.384798,
 9.387281,
 9.390261,
 9.391253,
 9.392994,
 9.395725,
 9.400693,
 9.401687,
 9.403423,
 9.407647,
 9.412119,
 9.417086,
 9.420811,
 9.421306,
 9.422797,
 9.424287,
 9.425776,
 9.43025,
 9.441673,
 9.456825,
 9.461793,
 9.462289,
 9.463035,
 9.463035,
 9.463531,
 9.469243,
 9.471727,
 9.474708,
 9.476447,
 9.476694,
 9.497808,
 9.50327,
 9.512461,
 9.52165,
 9.530343,
 9.53407,
 9.539782,
 9.546489,
 9.547233,
 9.554685,
 9.564868,
 9.574803,
 9.582254,
 9.585979,
 9.585979,
 9.599888,
 9.600137,
 9.601379,
 9.602125,
 9.609823,
 9.612059,
 9.61504,
 9.616282,
 9.624476,
 9.629943,
 9.639876,
 9.640373,
 9.647825,
 9.655275,
 9.670675,
 9.673903,
 9.675146,
 9.67912,
 9.684087,
 9.686323,
 9.686572,
 9.686572,
 9.689303,
 9.696008,
 9.696507,
 9.697252,
 9.698741,
 9.703958,
 9.708925,
 9.71141,
 9.713892,
 9.723081,
 9.733761,
 9.742206,
 9.756116,
 9.768534,
 9.773501,
 9.778221,
 9.790141,
 9.793369,
 9.804549,
 9.805294,
 9.805789,
 9.810262,
 9.811503,
 9.834848,
 9.836588,
 9.848013,
 9.850745,
 9.851243,
 9.856459,
 9.859687,
 9.860433,
 9.864902,
 9.888995,
 9.907127,
 9.907621,
 9.910108,
 9.910355,
 9.921532,
 9.933703,
 9.940161,
 9.947861,
 9.97071,
 9.979156,
 9.982135,
 9.984124,
 9.987846,
 9.988593,
 9.992568,
 9.996789,
 10.007471,
 10.008961,
 10.009208,
 10.010698,
 10.020633,
 10.02113,
 10.021875,
 10.02287,
 10.023862,
 10.02883,
 10.029573,
 10.033796,
 10.033796,
 10.035286,
 10.039757,
 10.039757,
 10.040254,
 10.042739,
 10.043235,
 10.047706,
 10.055654,
 10.056895,
 10.07304,
 10.07602,
 10.080243,
 10.086701,
 10.087942,
 10.098125,
 10.104336,
 10.105079,
 10.105577,
 10.117002,
 10.117498,
 10.130909,
 10.133147,
 10.133395,
 10.145812,
 10.153515,
 10.154259,
 10.157238,
 10.163448,
 10.165683,
 10.167421,
 10.173632,
 10.174873,
 10.180335,
 10.193005,
 10.193254,
 10.195738,
 10.199463,
 10.212625,
 10.226038,
 10.228274,
 10.248144,
 10.273229,
 10.284158,
 10.284902,
 10.28664,
 10.292602,
 10.294839,
 10.299805,
 10.304027,
 10.307504,
 10.311479,
 10.324891,
 10.326632,
 10.332343,
 10.341781,
 10.344015,
 10.351467,
 10.362892,
 10.363389,
 10.369349,
 10.374567,
 10.377298,
 10.380526,
 10.386984,
 10.398411,
 10.40586,
 10.406606,
 10.414554,
 10.41505,
 10.428462,
 10.43045,
 10.432436,
 10.433927,
 10.435417,
 10.44287,
 10.444109,
 10.447588,
 10.467954,
 10.471183,
 10.475157,
 10.495027,
 10.502726,
 10.510922,
 10.511171,
 10.518126,
 10.534516,
 10.538493,
 10.544951,
 10.545944,
 10.546937,
 10.548181,
 10.551904,
 10.563828,
 10.57997,
 10.582207,
 10.588911,
 10.593133,
 10.594625,
 10.59686,
 10.597854,
 10.601083,
 10.609528,
 10.613004,
 10.616482,
 10.617971,
 10.622691,
 10.627907,
 10.640326,
 10.64579,
 10.655229,
 10.655229,
 10.661934,
 10.673608,
 10.683542,
 10.683791,
 10.684289,
 10.686275,
 10.703163,
 10.705895,
 10.721045,
 10.72974,
 10.730733,
 10.744642,
 10.746132,
 10.747126,
 10.754579,
 10.763271,
 10.766747,
 10.768238,
 10.773205,
 10.775937,
 10.786121,
 10.806987,
 10.809964,
 10.81965,
 10.830829,
 10.835051,
 10.840265,
 10.84275,
 10.856411,
 10.862371,
 10.870318,
 10.876776,
 10.880752,
 10.882986,
 10.895654,
 10.897889,
 10.905589,
 10.907575,
 10.915772,
 10.918504,
 10.924465,
 10.924714,
 10.932911,
 10.935393,
 10.940113,
 10.940858,
 10.949551,
 10.952036,
 10.993015,
 11.001213,
 11.003198,
 11.003696,
 11.003696,
 11.004192,
 11.027041,
 11.029775,
 11.033997,
 11.035736,
 11.042689,
 11.047657,
 11.049893,
 11.050391,
 11.051384,
 11.058586,
 11.059581,
 11.059581,
 11.068521,
 11.082184,
 11.095346,
 11.098327,
 11.108011,
 11.119686,
 11.127137,
 11.132849,
 11.146262,
 11.155701,
 11.163152,
 11.165389,
 11.177309,
 11.181779,
 11.18327,
 11.185755,
 11.196186,
 11.201153,
 11.205126,
 11.20761,
 11.211338,
 11.218042,
 11.231703,
 11.243626,
 11.25033,
 11.251573,
 11.269456,
 11.274672,
 11.282619,
 11.29156,
 11.294044,
 11.294789,
 11.301745,
 11.303979,
 11.315405,
 11.316896,
 11.319875,
 11.330805,
 11.339497,
 11.339746,
 11.340987,
 11.351171,
 11.353159,
 11.36185,
 11.363587,
 11.363839,
 11.364333,
 11.375511,
 11.379484,
 11.38023,
 11.382714,
 11.388675,
 11.389917,
 11.390909,
 11.396126,
 11.402832,
 11.4155,
 11.416989,
 11.425187,
 11.433381,
 11.435371,
 11.437109,
 11.439095,
 11.448037,
 11.457475,
 11.461698,
 11.461698,
 11.466664,
 11.469397,
 11.470637,
 11.471881,
 11.472128,
 11.475357,
 11.475856,
 11.481816,
 11.48877,
 11.494732,
 11.497213,
 11.499699,
 11.504169,
 11.506901,
 11.515097,
 11.515346,
 11.52379,
 11.526274,
 11.529254,
 11.529254,
 11.534472,
 11.534718,
 11.537701,
 11.543162,
 11.547633,
 11.549374,
 11.555333,
 11.555583,
 11.565765,
 11.566759,
 11.567006,
 11.568746,
 11.572472,
 11.5757,
 11.578681,
 11.58042,
 11.581412,
 11.586629,
 11.592589,
 11.594328,
 11.596564,
 11.601779,
 11.603021,
 11.605753,
 11.608734,
 11.611218,
 11.611465,
 11.613702,
 11.619166,
 11.620407,
 11.623139,
 11.623886,
 11.62463,
 11.629101,
 11.638289,
 11.639532,
 11.642017,
 11.643755,
 11.648723,
 11.65071,
 11.654932,
 11.667601,
 11.671324,
 11.672068,
 11.673806,
 11.681009,
 11.681508,
 11.687965,
 11.688462,
 11.688959,
 11.696905,
 11.697405,
 11.698894,
 11.699142,
 11.700633,
 11.701378,
 11.702868,
 11.707585,
 11.707835,
 11.71032,
 11.711065,
 11.714045,
 11.714541,
 11.718266,
 11.724476,
 11.725223,
 11.725717,
 11.726711,
 11.737391,
 11.738136,
 11.738385,
 11.738882,
 11.740125,
 11.743104,
 11.744595,
 11.753784,
 11.755772,
 11.761733,
 11.766701,
 11.767445,
 11.772163,
 11.773405,
 11.776883,
 11.779614,
 11.781105,
 11.794765,
 11.797747,
 11.797996,
 11.800229,
 11.800728,
 11.802715,
 11.807434,
 11.809421,
 11.813145,
 11.818361,
 11.818857,
 11.819106,
 11.819106,
 11.822831,
 11.826058,
 11.827054,
 11.832271,
 11.836742,
 11.842951,
 11.84618,
 11.84916,
 11.850153,
 11.850403,
 11.851395,
 11.859838,
 11.860585,
 11.860832,
 11.87201,
 11.896849,
 11.897343,
 11.898338,
 11.899083,
 11.900077,
 11.918208,
 11.927397,
 11.929385,
 ...]

- The `dict` function converts the `Series` to a dictionary.
- The index labels become the keys.

In [39]:
dict(pokemon)

{0: 'Bulbasaur',
 1: 'Ivysaur',
 2: 'Venusaur',
 3: 'Charmander',
 4: 'Charmeleon',
 5: 'Charizard',
 6: 'Squirtle',
 7: 'Wartortle',
 8: 'Blastoise',
 9: 'Caterpie',
 10: 'Metapod',
 11: 'Butterfree',
 12: 'Weedle',
 13: 'Kakuna',
 14: 'Beedrill',
 15: 'Pidgey',
 16: 'Pidgeotto',
 17: 'Pidgeot',
 18: 'Rattata',
 19: 'Raticate',
 20: 'Spearow',
 21: 'Fearow',
 22: 'Ekans',
 23: 'Arbok',
 24: 'Pikachu',
 25: 'Raichu',
 26: 'Sandshrew',
 27: 'Sandslash',
 28: 'Nidoran♀',
 29: 'Nidorina',
 30: 'Nidoqueen',
 31: 'Nidoran♂',
 32: 'Nidorino',
 33: 'Nidoking',
 34: 'Clefairy',
 35: 'Clefable',
 36: 'Vulpix',
 37: 'Ninetales',
 38: 'Jigglypuff',
 39: 'Wigglytuff',
 40: 'Zubat',
 41: 'Golbat',
 42: 'Oddish',
 43: 'Gloom',
 44: 'Vileplume',
 45: 'Paras',
 46: 'Parasect',
 47: 'Venonat',
 48: 'Venomoth',
 49: 'Diglett',
 50: 'Dugtrio',
 51: 'Meowth',
 52: 'Persian',
 53: 'Psyduck',
 54: 'Golduck',
 55: 'Mankey',
 56: 'Primeape',
 57: 'Growlithe',
 58: 'Arcanine',
 59: 'Poliwag',
 60: 'Poliwhirl',
 61: 'Poliwrath',
 62: 'Abra',
 63: 'Kadabra',
 64: 'Alakazam',
 65: 'Machop',
 66: 'Machoke',
 67: 'Machamp',
 68: 'Bellsprout',
 69: 'Weepinbell',
 70: 'Victreebel',
 71: 'Tentacool',
 72: 'Tentacruel',
 73: 'Geodude',
 74: 'Graveler',
 75: 'Golem',
 76: 'Ponyta',
 77: 'Rapidash',
 78: 'Slowpoke',
 79: 'Slowbro',
 80: 'Magnemite',
 81: 'Magneton',
 82: 'Farfetch’d',
 83: 'Doduo',
 84: 'Dodrio',
 85: 'Seel',
 86: 'Dewgong',
 87: 'Grimer',
 88: 'Muk',
 89: 'Shellder',
 90: 'Cloyster',
 91: 'Gastly',
 92: 'Haunter',
 93: 'Gengar',
 94: 'Onix',
 95: 'Drowzee',
 96: 'Hypno',
 97: 'Krabby',
 98: 'Kingler',
 99: 'Voltorb',
 100: 'Electrode',
 101: 'Exeggcute',
 102: 'Exeggutor',
 103: 'Cubone',
 104: 'Marowak',
 105: 'Hitmonlee',
 106: 'Hitmonchan',
 107: 'Lickitung',
 108: 'Koffing',
 109: 'Weezing',
 110: 'Rhyhorn',
 111: 'Rhydon',
 112: 'Chansey',
 113: 'Tangela',
 114: 'Kangaskhan',
 115: 'Horsea',
 116: 'Seadra',
 117: 'Goldeen',
 118: 'Seaking',
 119: 'Staryu',
 120: 'Starmie',
 121: 'Mr. Mime',
 122: 'Scyther',
 123: 'Jynx',
 124: 'Electabuzz',
 125: 'Magmar',
 126: 'Pinsir',
 127: 'Tauros',
 128: 'Magikarp',
 129: 'Gyarados',
 130: 'Lapras',
 131: 'Ditto',
 132: 'Eevee',
 133: 'Vaporeon',
 134: 'Jolteon',
 135: 'Flareon',
 136: 'Porygon',
 137: 'Omanyte',
 138: 'Omastar',
 139: 'Kabuto',
 140: 'Kabutops',
 141: 'Aerodactyl',
 142: 'Snorlax',
 143: 'Articuno',
 144: 'Zapdos',
 145: 'Moltres',
 146: 'Dratini',
 147: 'Dragonair',
 148: 'Dragonite',
 149: 'Mewtwo',
 150: 'Mew',
 151: 'Chikorita',
 152: 'Bayleef',
 153: 'Meganium',
 154: 'Cyndaquil',
 155: 'Quilava',
 156: 'Typhlosion',
 157: 'Totodile',
 158: 'Croconaw',
 159: 'Feraligatr',
 160: 'Sentret',
 161: 'Furret',
 162: 'Hoothoot',
 163: 'Noctowl',
 164: 'Ledyba',
 165: 'Ledian',
 166: 'Spinarak',
 167: 'Ariados',
 168: 'Crobat',
 169: 'Chinchou',
 170: 'Lanturn',
 171: 'Pichu',
 172: 'Cleffa',
 173: 'Igglybuff',
 174: 'Togepi',
 175: 'Togetic',
 176: 'Natu',
 177: 'Xatu',
 178: 'Mareep',
 179: 'Flaaffy',
 180: 'Ampharos',
 181: 'Bellossom',
 182: 'Marill',
 183: 'Azumarill',
 184: 'Sudowoodo',
 185: 'Politoed',
 186: 'Hoppip',
 187: 'Skiploom',
 188: 'Jumpluff',
 189: 'Aipom',
 190: 'Sunkern',
 191: 'Sunflora',
 192: 'Yanma',
 193: 'Wooper',
 194: 'Quagsire',
 195: 'Espeon',
 196: 'Umbreon',
 197: 'Murkrow',
 198: 'Slowking',
 199: 'Misdreavus',
 200: 'Unown',
 201: 'Wobbuffet',
 202: 'Girafarig',
 203: 'Pineco',
 204: 'Forretress',
 205: 'Dunsparce',
 206: 'Gligar',
 207: 'Steelix',
 208: 'Snubbull',
 209: 'Granbull',
 210: 'Qwilfish',
 211: 'Scizor',
 212: 'Shuckle',
 213: 'Heracross',
 214: 'Sneasel',
 215: 'Teddiursa',
 216: 'Ursaring',
 217: 'Slugma',
 218: 'Magcargo',
 219: 'Swinub',
 220: 'Piloswine',
 221: 'Corsola',
 222: 'Remoraid',
 223: 'Octillery',
 224: 'Delibird',
 225: 'Mantine',
 226: 'Skarmory',
 227: 'Houndour',
 228: 'Houndoom',
 229: 'Kingdra',
 230: 'Phanpy',
 231: 'Donphan',
 232: 'Porygon2',
 233: 'Stantler',
 234: 'Smeargle',
 235: 'Tyrogue',
 236: 'Hitmontop',
 237: 'Smoochum',
 238: 'Elekid',
 239: 'Magby',
 240: 'Miltank',
 241: 'Blissey',
 242: 'Raikou',
 243: 'Entei',
 244: 'Suicune',
 245: 'Larvitar',
 246: 'Pupitar',
 247: 'Tyranitar',
 248: 'Lugia',
 249: 'Ho-Oh',
 250: 'Celebi',
 251: 'Treecko',
 252: 'Grovyle',
 253: 'Sceptile',
 254: 'Torchic',
 255: 'Combusken',
 256: 'Blaziken',
 257: 'Mudkip',
 258: 'Marshtomp',
 259: 'Swampert',
 260: 'Poochyena',
 261: 'Mightyena',
 262: 'Zigzagoon',
 263: 'Linoone',
 264: 'Wurmple',
 265: 'Silcoon',
 266: 'Beautifly',
 267: 'Cascoon',
 268: 'Dustox',
 269: 'Lotad',
 270: 'Lombre',
 271: 'Ludicolo',
 272: 'Seedot',
 273: 'Nuzleaf',
 274: 'Shiftry',
 275: 'Taillow',
 276: 'Swellow',
 277: 'Wingull',
 278: 'Pelipper',
 279: 'Ralts',
 280: 'Kirlia',
 281: 'Gardevoir',
 282: 'Surskit',
 283: 'Masquerain',
 284: 'Shroomish',
 285: 'Breloom',
 286: 'Slakoth',
 287: 'Vigoroth',
 288: 'Slaking',
 289: 'Nincada',
 290: 'Ninjask',
 291: 'Shedinja',
 292: 'Whismur',
 293: 'Loudred',
 294: 'Exploud',
 295: 'Makuhita',
 296: 'Hariyama',
 297: 'Azurill',
 298: 'Nosepass',
 299: 'Skitty',
 300: 'Delcatty',
 301: 'Sableye',
 302: 'Mawile',
 303: 'Aron',
 304: 'Lairon',
 305: 'Aggron',
 306: 'Meditite',
 307: 'Medicham',
 308: 'Electrike',
 309: 'Manectric',
 310: 'Plusle',
 311: 'Minun',
 312: 'Volbeat',
 313: 'Illumise',
 314: 'Roselia',
 315: 'Gulpin',
 316: 'Swalot',
 317: 'Carvanha',
 318: 'Sharpedo',
 319: 'Wailmer',
 320: 'Wailord',
 321: 'Numel',
 322: 'Camerupt',
 323: 'Torkoal',
 324: 'Spoink',
 325: 'Grumpig',
 326: 'Spinda',
 327: 'Trapinch',
 328: 'Vibrava',
 329: 'Flygon',
 330: 'Cacnea',
 331: 'Cacturne',
 332: 'Swablu',
 333: 'Altaria',
 334: 'Zangoose',
 335: 'Seviper',
 336: 'Lunatone',
 337: 'Solrock',
 338: 'Barboach',
 339: 'Whiscash',
 340: 'Corphish',
 341: 'Crawdaunt',
 342: 'Baltoy',
 343: 'Claydol',
 344: 'Lileep',
 345: 'Cradily',
 346: 'Anorith',
 347: 'Armaldo',
 348: 'Feebas',
 349: 'Milotic',
 350: 'Castform',
 351: 'Kecleon',
 352: 'Shuppet',
 353: 'Banette',
 354: 'Duskull',
 355: 'Dusclops',
 356: 'Tropius',
 357: 'Chimecho',
 358: 'Absol',
 359: 'Wynaut',
 360: 'Snorunt',
 361: 'Glalie',
 362: 'Spheal',
 363: 'Sealeo',
 364: 'Walrein',
 365: 'Clamperl',
 366: 'Huntail',
 367: 'Gorebyss',
 368: 'Relicanth',
 369: 'Luvdisc',
 370: 'Bagon',
 371: 'Shelgon',
 372: 'Salamence',
 373: 'Beldum',
 374: 'Metang',
 375: 'Metagross',
 376: 'Regirock',
 377: 'Regice',
 378: 'Registeel',
 379: 'Latias',
 380: 'Latios',
 381: 'Kyogre',
 382: 'Groudon',
 383: 'Rayquaza',
 384: 'Jirachi',
 385: 'Deoxys',
 386: 'Turtwig',
 387: 'Grotle',
 388: 'Torterra',
 389: 'Chimchar',
 390: 'Monferno',
 391: 'Infernape',
 392: 'Piplup',
 393: 'Prinplup',
 394: 'Empoleon',
 395: 'Starly',
 396: 'Staravia',
 397: 'Staraptor',
 398: 'Bidoof',
 399: 'Bibarel',
 400: 'Kricketot',
 401: 'Kricketune',
 402: 'Shinx',
 403: 'Luxio',
 404: 'Luxray',
 405: 'Budew',
 406: 'Roserade',
 407: 'Cranidos',
 408: 'Rampardos',
 409: 'Shieldon',
 410: 'Bastiodon',
 411: 'Burmy',
 412: 'Wormadam',
 413: 'Mothim',
 414: 'Combee',
 415: 'Vespiquen',
 416: 'Pachirisu',
 417: 'Buizel',
 418: 'Floatzel',
 419: 'Cherubi',
 420: 'Cherrim',
 421: 'Shellos',
 422: 'Gastrodon',
 423: 'Ambipom',
 424: 'Drifloon',
 425: 'Drifblim',
 426: 'Buneary',
 427: 'Lopunny',
 428: 'Mismagius',
 429: 'Honchkrow',
 430: 'Glameow',
 431: 'Purugly',
 432: 'Chingling',
 433: 'Stunky',
 434: 'Skuntank',
 435: 'Bronzor',
 436: 'Bronzong',
 437: 'Bonsly',
 438: 'Mime Jr.',
 439: 'Happiny',
 440: 'Chatot',
 441: 'Spiritomb',
 442: 'Gible',
 443: 'Gabite',
 444: 'Garchomp',
 445: 'Munchlax',
 446: 'Riolu',
 447: 'Lucario',
 448: 'Hippopotas',
 449: 'Hippowdon',
 450: 'Skorupi',
 451: 'Drapion',
 452: 'Croagunk',
 453: 'Toxicroak',
 454: 'Carnivine',
 455: 'Finneon',
 456: 'Lumineon',
 457: 'Mantyke',
 458: 'Snover',
 459: 'Abomasnow',
 460: 'Weavile',
 461: 'Magnezone',
 462: 'Lickilicky',
 463: 'Rhyperior',
 464: 'Tangrowth',
 465: 'Electivire',
 466: 'Magmortar',
 467: 'Togekiss',
 468: 'Yanmega',
 469: 'Leafeon',
 470: 'Glaceon',
 471: 'Gliscor',
 472: 'Mamoswine',
 473: 'Porygon-Z',
 474: 'Gallade',
 475: 'Probopass',
 476: 'Dusknoir',
 477: 'Froslass',
 478: 'Rotom',
 479: 'Uxie',
 480: 'Mesprit',
 481: 'Azelf',
 482: 'Dialga',
 483: 'Palkia',
 484: 'Heatran',
 485: 'Regigigas',
 486: 'Giratina',
 487: 'Cresselia',
 488: 'Phione',
 489: 'Manaphy',
 490: 'Darkrai',
 491: 'Shaymin',
 492: 'Arceus',
 493: 'Victini',
 494: 'Snivy',
 495: 'Servine',
 496: 'Serperior',
 497: 'Tepig',
 498: 'Pignite',
 499: 'Emboar',
 500: 'Oshawott',
 501: 'Dewott',
 502: 'Samurott',
 503: 'Patrat',
 504: 'Watchog',
 505: 'Lillipup',
 506: 'Herdier',
 507: 'Stoutland',
 508: 'Purrloin',
 509: 'Liepard',
 510: 'Pansage',
 511: 'Simisage',
 512: 'Pansear',
 513: 'Simisear',
 514: 'Panpour',
 515: 'Simipour',
 516: 'Munna',
 517: 'Musharna',
 518: 'Pidove',
 519: 'Tranquill',
 520: 'Unfezant',
 521: 'Blitzle',
 522: 'Zebstrika',
 523: 'Roggenrola',
 524: 'Boldore',
 525: 'Gigalith',
 526: 'Woobat',
 527: 'Swoobat',
 528: 'Drilbur',
 529: 'Excadrill',
 530: 'Audino',
 531: 'Timburr',
 532: 'Gurdurr',
 533: 'Conkeldurr',
 534: 'Tympole',
 535: 'Palpitoad',
 536: 'Seismitoad',
 537: 'Throh',
 538: 'Sawk',
 539: 'Sewaddle',
 540: 'Swadloon',
 541: 'Leavanny',
 542: 'Venipede',
 543: 'Whirlipede',
 544: 'Scolipede',
 545: 'Cottonee',
 546: 'Whimsicott',
 547: 'Petilil',
 548: 'Lilligant',
 549: 'Basculin',
 550: 'Sandile',
 551: 'Krokorok',
 552: 'Krookodile',
 553: 'Darumaka',
 554: 'Darmanitan',
 555: 'Maractus',
 556: 'Dwebble',
 557: 'Crustle',
 558: 'Scraggy',
 559: 'Scrafty',
 560: 'Sigilyph',
 561: 'Yamask',
 562: 'Cofagrigus',
 563: 'Tirtouga',
 564: 'Carracosta',
 565: 'Archen',
 566: 'Archeops',
 567: 'Trubbish',
 568: 'Garbodor',
 569: 'Zorua',
 570: 'Zoroark',
 571: 'Minccino',
 572: 'Cinccino',
 573: 'Gothita',
 574: 'Gothorita',
 575: 'Gothitelle',
 576: 'Solosis',
 577: 'Duosion',
 578: 'Reuniclus',
 579: 'Ducklett',
 580: 'Swanna',
 581: 'Vanillite',
 582: 'Vanillish',
 583: 'Vanilluxe',
 584: 'Deerling',
 585: 'Sawsbuck',
 586: 'Emolga',
 587: 'Karrablast',
 588: 'Escavalier',
 589: 'Foongus',
 590: 'Amoonguss',
 591: 'Frillish',
 592: 'Jellicent',
 593: 'Alomomola',
 594: 'Joltik',
 595: 'Galvantula',
 596: 'Ferroseed',
 597: 'Ferrothorn',
 598: 'Klink',
 599: 'Klang',
 600: 'Klinklang',
 601: 'Tynamo',
 602: 'Eelektrik',
 603: 'Eelektross',
 604: 'Elgyem',
 605: 'Beheeyem',
 606: 'Litwick',
 607: 'Lampent',
 608: 'Chandelure',
 609: 'Axew',
 610: 'Fraxure',
 611: 'Haxorus',
 612: 'Cubchoo',
 613: 'Beartic',
 614: 'Cryogonal',
 615: 'Shelmet',
 616: 'Accelgor',
 617: 'Stunfisk',
 618: 'Mienfoo',
 619: 'Mienshao',
 620: 'Druddigon',
 621: 'Golett',
 622: 'Golurk',
 623: 'Pawniard',
 624: 'Bisharp',
 625: 'Bouffalant',
 626: 'Rufflet',
 627: 'Braviary',
 628: 'Vullaby',
 629: 'Mandibuzz',
 630: 'Heatmor',
 631: 'Durant',
 632: 'Deino',
 633: 'Zweilous',
 634: 'Hydreigon',
 635: 'Larvesta',
 636: 'Volcarona',
 637: 'Cobalion',
 638: 'Terrakion',
 639: 'Virizion',
 640: 'Tornadus',
 641: 'Thundurus',
 642: 'Reshiram',
 643: 'Zekrom',
 644: 'Landorus',
 645: 'Kyurem',
 646: 'Keldeo',
 647: 'Meloetta',
 648: 'Genesect',
 649: 'Chespin',
 650: 'Quilladin',
 651: 'Chesnaught',
 652: 'Fennekin',
 653: 'Braixen',
 654: 'Delphox',
 655: 'Froakie',
 656: 'Frogadier',
 657: 'Greninja',
 658: 'Bunnelby',
 659: 'Diggersby',
 660: 'Fletchling',
 661: 'Fletchinder',
 662: 'Talonflame',
 663: 'Scatterbug',
 664: 'Spewpa',
 665: 'Vivillon',
 666: 'Litleo',
 667: 'Pyroar',
 668: 'Flabébé',
 669: 'Floette',
 670: 'Florges',
 671: 'Skiddo',
 672: 'Gogoat',
 673: 'Pancham',
 674: 'Pangoro',
 675: 'Furfrou',
 676: 'Espurr',
 677: 'Meowstic',
 678: 'Honedge',
 679: 'Doublade',
 680: 'Aegislash',
 681: 'Spritzee',
 682: 'Aromatisse',
 683: 'Swirlix',
 684: 'Slurpuff',
 685: 'Inkay',
 686: 'Malamar',
 687: 'Binacle',
 688: 'Barbaracle',
 689: 'Skrelp',
 690: 'Dragalge',
 691: 'Clauncher',
 692: 'Clawitzer',
 693: 'Helioptile',
 694: 'Heliolisk',
 695: 'Tyrunt',
 696: 'Tyrantrum',
 697: 'Amaura',
 698: 'Aurorus',
 699: 'Sylveon',
 700: 'Hawlucha',
 701: 'Dedenne',
 702: 'Carbink',
 703: 'Goomy',
 704: 'Sliggoo',
 705: 'Goodra',
 706: 'Klefki',
 707: 'Phantump',
 708: 'Trevenant',
 709: 'Pumpkaboo',
 710: 'Gourgeist',
 711: 'Bergmite',
 712: 'Avalugg',
 713: 'Noibat',
 714: 'Noivern',
 715: 'Xerneas',
 716: 'Yveltal',
 717: 'Zygarde',
 718: 'Diancie',
 719: 'Hoopa',
 720: 'Volcanion',
 721: 'Rowlet',
 722: 'Dartrix',
 723: 'Decidueye',
 724: 'Litten',
 725: 'Torracat',
 726: 'Incineroar',
 727: 'Popplio',
 728: 'Brionne',
 729: 'Primarina',
 730: 'Pikipek',
 731: 'Trumbeak',
 732: 'Toucannon',
 733: 'Yungoos',
 734: 'Gumshoos',
 735: 'Grubbin',
 736: 'Charjabug',
 737: 'Vikavolt',
 738: 'Crabrawler',
 739: 'Crabominable',
 740: 'Oricorio',
 741: 'Cutiefly',
 742: 'Ribombee',
 743: 'Rockruff',
 744: 'Lycanroc',
 745: 'Wishiwashi',
 746: 'Mareanie',
 747: 'Toxapex',
 748: 'Mudbray',
 749: 'Mudsdale',
 750: 'Dewpider',
 751: 'Araquanid',
 752: 'Fomantis',
 753: 'Lurantis',
 754: 'Morelull',
 755: 'Shiinotic',
 756: 'Salandit',
 757: 'Salazzle',
 758: 'Stufful',
 759: 'Bewear',
 760: 'Bounsweet',
 761: 'Steenee',
 762: 'Tsareena',
 763: 'Comfey',
 764: 'Oranguru',
 765: 'Passimian',
 766: 'Wimpod',
 767: 'Golisopod',
 768: 'Sandygast',
 769: 'Palossand',
 770: 'Pyukumuku',
 771: 'Type: Null',
 772: 'Silvally',
 773: 'Minior',
 774: 'Komala',
 775: 'Turtonator',
 776: 'Togedemaru',
 777: 'Mimikyu',
 778: 'Bruxish',
 779: 'Drampa',
 780: 'Dhelmise',
 781: 'Jangmo-o',
 782: 'Hakamo-o',
 783: 'Kommo-o',
 784: 'Tapu Koko',
 785: 'Tapu Lele',
 786: 'Tapu Bulu',
 787: 'Tapu Fini',
 788: 'Cosmog',
 789: 'Cosmoem',
 790: 'Solgaleo',
 791: 'Lunala',
 792: 'Nihilego',
 793: 'Buzzwole',
 794: 'Pheromosa',
 795: 'Xurkitree',
 796: 'Celesteela',
 797: 'Kartana',
 798: 'Guzzlord',
 799: 'Necrozma',
 800: 'Magearna',
 801: 'Marshadow',
 802: 'Poipole',
 803: 'Naganadel',
 804: 'Stakataka',
 805: 'Blacephalon',
 806: 'Zeraora',
 807: 'Meltan',
 808: 'Melmetal',
 809: 'Grookey',
 810: 'Thwackey',
 811: 'Rillaboom',
 812: 'Scorbunny',
 813: 'Raboot',
 814: 'Cinderace',
 815: 'Sobble',
 816: 'Drizzile',
 817: 'Inteleon',
 818: 'Skwovet',
 819: 'Greedent',
 820: 'Rookidee',
 821: 'Corvisquire',
 822: 'Corviknight',
 823: 'Blipbug',
 824: 'Dottler',
 825: 'Orbeetle',
 826: 'Nickit',
 827: 'Thievul',
 828: 'Gossifleur',
 829: 'Eldegoss',
 830: 'Wooloo',
 831: 'Dubwool',
 832: 'Chewtle',
 833: 'Drednaw',
 834: 'Yamper',
 835: 'Boltund',
 836: 'Rolycoly',
 837: 'Carkol',
 838: 'Coalossal',
 839: 'Applin',
 840: 'Flapple',
 841: 'Appletun',
 842: 'Silicobra',
 843: 'Sandaconda',
 844: 'Cramorant',
 845: 'Arrokuda',
 846: 'Barraskewda',
 847: 'Toxel',
 848: 'Toxtricity',
 849: 'Sizzlipede',
 850: 'Centiskorch',
 851: 'Clobbopus',
 852: 'Grapploct',
 853: 'Sinistea',
 854: 'Polteageist',
 855: 'Hatenna',
 856: 'Hattrem',
 857: 'Hatterene',
 858: 'Impidimp',
 859: 'Morgrem',
 860: 'Grimmsnarl',
 861: 'Obstagoon',
 862: 'Perrserker',
 863: 'Cursola',
 864: 'Sirfetch’d',
 865: 'Mr. Rime',
 866: 'Runerigus',
 867: 'Milcery',
 868: 'Alcremie',
 869: 'Falinks',
 870: 'Pincurchin',
 871: 'Snom',
 872: 'Frosmoth',
 873: 'Stonjourner',
 874: 'Eiscue',
 875: 'Indeedee',
 876: 'Morpeko',
 877: 'Cufant',
 878: 'Copperajah',
 879: 'Dracozolt',
 880: 'Arctozolt',
 881: 'Dracovish',
 882: 'Arctovish',
 883: 'Duraludon',
 884: 'Dreepy',
 885: 'Drakloak',
 886: 'Dragapult',
 887: 'Zacian',
 888: 'Zamazenta',
 889: 'Eternatus',
 890: 'Kubfu',
 891: 'Urshifu',
 892: 'Zarude',
 893: 'Regieleki',
 894: 'Regidrago',
 895: 'Glastrier',
 896: 'Spectrier',
 897: 'Calyrex',
 898: 'Wyrdeer',
 899: 'Kleavor',
 900: 'Ursaluna',
 901: 'Basculegion',
 902: 'Sneasler',
 903: 'Overqwil',
 904: 'Enamorus',
 905: 'Sprigatito',
 906: 'Floragato',
 907: 'Meowscarada',
 908: 'Fuecoco',
 909: 'Crocalor',
 910: 'Skeledirge',
 911: 'Quaxly',
 912: 'Quaxwell',
 913: 'Quaquaval',
 914: 'Lechonk',
 915: 'Oinkologne',
 916: 'Tarountula',
 917: 'Spidops',
 918: 'Nymble',
 919: 'Lokix',
 920: 'Pawmi',
 921: 'Pawmo',
 922: 'Pawmot',
 923: 'Tandemaus',
 924: 'Maushold',
 925: 'Fidough',
 926: 'Dachsbun',
 927: 'Smoliv',
 928: 'Dolliv',
 929: 'Arboliva',
 930: 'Squawkabilly',
 931: 'Nacli',
 932: 'Naclstack',
 933: 'Garganacl',
 934: 'Charcadet',
 935: 'Armarouge',
 936: 'Ceruledge',
 937: 'Tadbulb',
 938: 'Bellibolt',
 939: 'Wattrel',
 940: 'Kilowattrel',
 941: 'Maschiff',
 942: 'Mabosstiff',
 943: 'Shroodle',
 944: 'Grafaiai',
 945: 'Bramblin',
 946: 'Brambleghast',
 947: 'Toedscool',
 948: 'Toedscruel',
 949: 'Klawf',
 950: 'Capsakid',
 951: 'Scovillain',
 952: 'Rellor',
 953: 'Rabsca',
 954: 'Flittle',
 955: 'Espathra',
 956: 'Tinkatink',
 957: 'Tinkatuff',
 958: 'Tinkaton',
 959: 'Wiglett',
 960: 'Wugtrio',
 961: 'Bombirdier',
 962: 'Finizen',
 963: 'Palafin',
 964: 'Varoom',
 965: 'Revavroom',
 966: 'Cyclizar',
 967: 'Orthworm',
 968: 'Glimmet',
 969: 'Glimmora',
 970: 'Greavard',
 971: 'Houndstone',
 972: 'Flamigo',
 973: 'Cetoddle',
 974: 'Cetitan',
 975: 'Veluza',
 976: 'Dondozo',
 977: 'Tatsugiri',
 978: 'Annihilape',
 979: 'Clodsire',
 980: 'Farigiraf',
 981: 'Dudunsparce',
 982: 'Kingambit',
 983: 'Great Tusk',
 984: 'Scream Tail',
 985: 'Brute Bonnet',
 986: 'Flutter Mane',
 987: 'Slither Wing',
 988: 'Sandy Shocks',
 989: 'Iron Treads',
 990: 'Iron Bundle',
 991: 'Iron Hands',
 992: 'Iron Jugulis',
 993: 'Iron Moth',
 994: 'Iron Thorns',
 995: 'Frigibax',
 996: 'Arctibax',
 997: 'Baxcalibur',
 998: 'Gimmighoul',
 999: 'Gholdengo',
 ...}

- The `max` function returns the largest value in the `Series`.
- The `min` function returns the smallest value in the `Series`.
- The largest value in a string `Series` is the string closest to the end of the alphabet.

In [40]:
max(google)
min(google)

2.483985

In [41]:
max(pokemon)
min(pokemon)

'Abomasnow'

- The `dir` function returns a list of strings with the object's attributes/methods.

In [42]:
dir(pokemon)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_attrs',
 '_binop',
 '_can_hold_na',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'between',
 'between_time',
 'bfill',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

## Check for Inclusion with Python's in Keyword
- The `in` keyword checks if a value exists within an object.
- The `in` keyword will look for a value in the `Series`'s index.
- Use the `index` and `array` attributes to access "nested" objects within the `Series`.
- Combine the `in` keyword with `array` to search within the `Series`'s values.

In [43]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

In [44]:
"car" in "racecar"
2 in [2, 3, 1]

True

In [45]:
"Bulbasaur" in pokemon

False

In [46]:
0 in pokemon
0 in pokemon.index
100 in pokemon.index

True

- Use the `array` attribute to access the underlying object storing the `Series` data.
- The object may vary but it should support Python's `in` keyword to check for inclusion.
- The `values` attribute also works, but the Pandas documentation recommends `array`.

In [47]:
"Bulbasaur" in pokemon.values

True

In [48]:
"Bulbasaur" in pokemon.array

True

## The sort_values Method
- The `sort_values` method sorts a `Series's` values in order.
- By default, pandas applies an ascending sort (smallest to largest).
- Customize the sort order with the `ascending` parameter.
- The index positions/labels will move with the values.

In [49]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

In [50]:
google.sort_values()
google.sort_values(ascending=True)
google.sort_values(ascending=False)

5395    338.250000
5396    338.000000
5394    336.010010
5384    335.970001
5385    335.839996
           ...
12        2.522979
10        2.521240
0         2.492181
9         2.489945
11        2.483985
Name: Price, Length: 5397, dtype: float64

In [51]:
pokemon.sort_values()
pokemon.sort_values(ascending=True)
pokemon.sort_values(ascending=False)

717      Zygarde
633     Zweilous
40         Zubat
569        Zorua
570      Zoroark
         ...
680    Aegislash
616     Accelgor
358        Absol
62          Abra
459    Abomasnow
Name: Name, Length: 1010, dtype: str

In [52]:
pokemon

0          Bulbasaur
1            Ivysaur
2           Venusaur
3         Charmander
4         Charmeleon
            ...
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, Length: 1010, dtype: str

## The sort_index Method
- The `sort_index` method sorts a `Series` by its index.
- The `sort_index` method also accepts an `ascending` parameter to set the sort order.

In [53]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

In [54]:
pokemon.sort_index()
pokemon.sort_values().sort_index()
pokemon.sort_index(ascending=True)
pokemon.sort_index(ascending=False)

1009     Iron Leaves
1008    Walking Wake
1007        Miraidon
1006        Koraidon
1005    Iron Valiant
            ...
4         Charmeleon
3         Charmander
2           Venusaur
1            Ivysaur
0          Bulbasaur
Name: Name, Length: 1010, dtype: str

- The `index_col` parameter to `read_csv` sets the index column.

In [55]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
pokemon

Name
Bulbasaur          Grass, Poison
Ivysaur            Grass, Poison
Venusaur           Grass, Poison
Charmander                  Fire
Charmeleon                  Fire
                      ...
Iron Valiant     Fairy, Fighting
Koraidon        Fighting, Dragon
Miraidon        Electric, Dragon
Walking Wake       Water, Dragon
Iron Leaves       Grass, Psychic
Name: Type, Length: 1010, dtype: str

In [56]:
pokemon.sort_index()

Name
Abomasnow        Grass, Ice
Abra                Psychic
Absol                  Dark
Accelgor                Bug
Aegislash      Steel, Ghost
                  ...
Zoroark                Dark
Zorua                  Dark
Zubat        Poison, Flying
Zweilous       Dark, Dragon
Zygarde      Dragon, Ground
Name: Type, Length: 1010, dtype: str

## Extract Series Value by Index Position
- Use the `iloc` accessor to extract a `Series` value by its index position.
- `iloc` is short for "index location".

In [57]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

- Provide square brackets after the accessor. Declare the index position inside the square brackets.

In [58]:
pokemon.iloc[0]
pokemon.iloc[500]

'Oshawott'

- A nonexistent index will trigger an exception.

In [59]:
# pokemon.iloc[1500]

- Pass a Python list to extract multiple `Series` values by their index positions.

In [60]:
pokemon.iloc[[100, 200, 300]]

# pokemon.iloc[[100, 200, 300, 1500]]

100    Electrode
200        Unown
300     Delcatty
Name: Name, dtype: str

- The `Series` support's Python's list slicing syntaxes (slices, slices from start, slices to end, etc.) are supported with `Series` objects.

In [61]:
pokemon.iloc[27:36]
pokemon.iloc[0:7]
pokemon.iloc[:7]

pokemon.iloc[700:1500]
pokemon.iloc[700:]

700         Hawlucha
701          Dedenne
702          Carbink
703            Goomy
704          Sliggoo
            ...
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, Length: 310, dtype: str

- Pandas also supports negative values and negative slices.
- -1 pulls the last value, -10 pulls the value 10 from the end.
- The second number is exclusive. `-10:-5` will pull the value 10 from the end up until (but not including) 5 from the end.

In [62]:
pokemon.iloc[-1]
pokemon.iloc[-10]
pokemon.iloc[-10:-5]
pokemon.iloc[-8:]

1002         Ting-Lu
1003          Chi-Yu
1004    Roaring Moon
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, dtype: str

- The `iat` accessor accepts only a single index value.
- The `iat` accessor does _not_ support lists or slices.
- The advantage of the restriction is that access is generally faster than `iloc`.
- Pandas does not need to figure out the argument type.

In [63]:
pokemon.iat[1]

'Ivysaur'

## Extract Series Value by Index Label
- Use the `loc` accessor to extract a `Series` value by its index label.
- Pass a list to extract multiple values by index label.
- If one index label/position in the list does not exist, Pandas will raise an error.

In [64]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns").sort_index()
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

pokemon.head()

Name
Abomasnow      Grass, Ice
Abra              Psychic
Absol                Dark
Accelgor              Bug
Aegislash    Steel, Ghost
Name: Type, dtype: str

In [65]:
pokemon.loc["Bulbasaur"]

'Grass, Poison'

In [66]:
# pokemon.loc["Digimon"]

In [67]:
pokemon.loc[["Charizard", "Jolteon"]]

pokemon.loc[["Jolteon", "Charizard"]]

Name
Jolteon          Electric
Charizard    Fire, Flying
Name: Type, dtype: str

In [68]:
# pokemon.loc[["Jolteon", "Charizard", "Digimon"]]

In [69]:
pokemon.loc["Bulbasaur":"Cascoon"]

Name
Bulbasaur      Grass, Poison
Buneary               Normal
Bunnelby              Normal
Burmy                    Bug
Butterfree       Bug, Flying
Buzzwole       Bug, Fighting
Cacnea                 Grass
Cacturne         Grass, Dark
Calyrex       Psychic, Grass
Camerupt        Fire, Ground
Capsakid               Grass
Carbink          Rock, Fairy
Carkol            Rock, Fire
Carnivine              Grass
Carracosta       Water, Rock
Carvanha         Water, Dark
Cascoon                  Bug
Name: Type, dtype: str

- The `at` accessor is complementary to `loc`, much like `iat` is complementary to `iloc`.
- It only supports a single index label. It does not support slices or lists. The constraint enables it to be faster for single-index targets.

In [70]:
pokemon.at["Bulbasaur"]

'Grass, Poison'

In [71]:
pokemon.iloc[100]

'Grass, Dark'

## The get Method on a Series
- The `get` method extracts a `Series` value by index label. It is an alternative option to square brackets.

In [72]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns").sort_index()
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

In [73]:
pokemon.get("Moltres")
pokemon.loc["Moltres"]
pokemon.at["Moltres"]

'Fire, Flying'

- The `get` method accepts a list of multiple index labels.

In [74]:
pokemon.get(["Moltres", "Dragonite"])

Name
Moltres        Fire, Flying
Dragonite    Dragon, Flying
Name: Type, dtype: str

- Square brackets raise an exception if the key does not exist.
- The `get` method's second argument sets the fallback value to return if the label/position does not exist.
- The default value for the default is `None`, which has no printed representation.

In [75]:
# pokemon.loc["Digimon"]
print(pokemon.get("Digimon"))

None

In [76]:
pokemon.get("Digimon", "Nonexistent")

'Nonexistent'

In [77]:
pokemon.get("Moltres", "Nonexistent")

'Fire, Flying'

- We can also a pass list to extract multiple elements.

In [78]:
pokemon.get(["Moltres", "Digimon"], "One of the values in the list was not found")

'One of the values in the list was not found'

## Overwrite a Series Value
- Use the `loc`/`iloc` accessor to target an index label/position, then use an equal sign to provide a new value.

In [79]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

pokemon.head()

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str

In [80]:
pokemon.iloc[0] = "Borisaur"

In [81]:
pokemon.head()

0      Borisaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str

In [82]:
pokemon.iloc[[1, 2, 4]] = ["Firemon", "Flamemon", "Blazemon"]

In [83]:
pokemon.head()

0      Borisaur
1       Firemon
2      Flamemon
3    Charmander
4      Blazemon
Name: Name, dtype: str

In [84]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

pokemon.head()

Name
Bulbasaur     Grass, Poison
Ivysaur       Grass, Poison
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

In [85]:
pokemon.loc["Bulbasaur"] = "Green Energy"

In [86]:
pokemon.head()

Name
Bulbasaur      Green Energy
Ivysaur       Grass, Poison
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

- The `Series` maintains a numeric order of values even if the index is not numeric.

In [87]:
pokemon.iloc[1] = "Serious Gas"

In [88]:
pokemon.head()

Name
Bulbasaur      Green Energy
Ivysaur         Serious Gas
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

## Copy-on-Write and the copy Method
- In earlier versions of Pandas (`< 3.0`), targeting data could return a view.
- A view was a window/alternate perspective into the *same* underlying data.
- Changes to the view would mutate the original object that the view was referencing.
- Pandas 3.0 follows a **Copy-on-Write** principle.
    1. Any object derived from another behaves as an independent copy.
    2. When code mutates the underlying data, Pandas will create a copy to avoid unexpected side effects.
- A **copy** is a duplicate/clone of an object.

- Let's assign the imported `DataFrame` to a `pokemon_df` variable.
- We'll then use it as the basis of creating a `Series` assigned to `pokemon_series`.
- `pokemon_series` share the same data under the hood as the `DataFrame`.
- Pandas has no reason to copy the data yet (and use more memory).

In [89]:
pd.__version__

'3.0.5'

In [90]:
pokemon_df = pd.read_csv("pokemon.csv", usecols=["Name"])
pokemon_series = pokemon_df.squeeze("columns")

- Let's use the `iloc` accesor to update the `Series` at index position 0.
- Pandas sees the mutation of the underlying data. It creates a copy of the data for the `Series`.

In [91]:
pokemon_series.iloc[0] = "Borisaur"

In [92]:
pokemon_series.head()

0      Borisaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str

- The original `pokemon_df` `DataFrame` is **not** mutated.
- The Copy-on-Write principle in Pandas 3 force a copy of the `Series` data when we mutate it (`iloc`).
- `pokemon_series` _was_ relying on shared data before `iloc` but now has its own copy of the data.

In [93]:
pokemon_df

              Name
0        Bulbasaur
1          Ivysaur
2         Venusaur
3       Charmander
4       Charmeleon
...            ...
1005  Iron Valiant
1006      Koraidon
1007      Miraidon
1008  Walking Wake
1009   Iron Leaves

[1010 rows x 1 columns]

- In previous version of Pandas, we would see different behavior.
- Mutating the `Series` would mutate the `DataFrame` as well.
- In previous versions, invoke the `copy` method explicitly to force a copy of the `Series` data.

In [94]:
pokemon_df = pd.read_csv("pokemon.csv", usecols=["Name"])
pokemon_series = pokemon_df.squeeze("columns").copy()

## Math Methods on Series

In [95]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

- The `count` method returns the number of present values in the `Series`.
- The `count` method excludes missing values.
- The `size` attribute includes missing values (the `len` function is another option).

In [96]:
google.count()

np.int64(5397)

In [97]:
google.size
len(google)

5397

In [98]:
pd.Series([1, 2, None]).count()
pd.Series([1, 2, None]).size
len(pd.Series([1, 2, None]))
pd.Series([1, 2, None])

0    1.0
1    2.0
2    NaN
dtype: float64

- The `sum` method adds together the `Series`'s values.

In [99]:
google.sum()

np.float64(303042.036389)

- The `product` method multiplies together the `Series`'s values.

In [100]:
print(pd.Series([1, 2, 3, 4]).product())

24

- The `mean` method calculates the average of the `Series`'s values.

In [101]:
google.mean()

np.float64(56.15009012210488)

- The `std` method calculates the standard deviation of the `Series`'s values.

In [102]:
google.std()

59.70900997580962

- The `max` method returns the largest value in the `Series`.
- The `min` method returns the smallest value in the `Series`.

In [103]:
google.max()
# google.min()

338.25

- The `idxmin` and `idxmax` methods return the index label where the smallest/largest value occurs.

In [104]:
google.idxmax()

5395

In [105]:
google.idxmin()

11

- We can confirm the value is correct by extracting it by the index.

In [106]:
google.loc[google.idxmax()]

np.float64(338.25)


- The `median` method returns the median of the `Series` (the value in the middle).

In [107]:
google.median()

29.434601

- The `mode` method returns the mode of the `Series` (the most frequent value).

In [108]:
pd.Series([1, 2, 2, 2, 3]).mode()

0    2
dtype: int64

- The `describe` method returns a summary with various mathematical calculations.
- The output includes the quartiles. 25% of the values are less than or equal to 13.295.

In [109]:
google.describe()

count    5397.000000
mean       56.150090
std        59.709010
min         2.483985
25%        13.295440
50%        29.434601
75%        76.341682
max       338.250000
Name: Price, dtype: float64

- The `quantile` method returns any percentile.
- The argument should be a decimal between 0 and 1.

In [110]:
google.quantile(0.25)
google.quantile(0.4)

np.float64(19.883351800000003)

- The `quantile` method accepts a list of multiple percentiles.
- Pandas will return a `Series`. The index labels will be the percentiles.

In [111]:
google.quantile([0.1, 0.25, 0.5, 0.75, 0.9])

0.10      9.627756
0.25     13.295440
0.50     29.434601
0.75     76.341682
0.90    142.289694
Name: Price, dtype: float64

## Broadcasting
- **Broadcasting** is the process of applying a consistent mathematical operation to every `Series` value.
- Use a mathematical operator with a `Series` to apply the mathematical operation to every value.
- There are also methods to accomplish the same results (`add`, `sub`, `mul`, `div`, etc.)

In [112]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

- Wrap the operation in parentheses to invoke a method upon the resulting object.
- Alternatively, assign the result to a variable.

In [113]:
google + 10
google.add(10)
(google + 10).head()

0    12.492181
1    12.690134
2    12.717208
3    12.604694
4    12.632761
Name: Price, dtype: float64

- Use `-` for subtraction, `*` for multiplication, `/` for division, and `//` for floor division.
- We can reverse the operands around the operator if the operation is logically the same.

In [114]:
google - 30
google.sub(30)

0       -27.507819
1       -27.309866
2       -27.282792
3       -27.395306
4       -27.367239
           ...
5392    303.260010
5393    304.549988
5394    306.010010
5395    308.250000
5396    308.000000
Name: Price, Length: 5397, dtype: float64

In [115]:
google * 1.25
google.mul(1.25)
1.25 * google

0         3.115226
1         3.362668
2         3.396510
3         3.255867
4         3.290951
           ...
5392    416.575013
5393    418.187485
5394    420.012513
5395    422.812500
5396    422.500000
Name: Price, Length: 5397, dtype: float64

In [116]:
google / 2
google.div(2)

0         1.246090
1         1.345067
2         1.358604
3         1.302347
4         1.316380
           ...
5392    166.630005
5393    167.274994
5394    168.005005
5395    169.125000
5396    169.000000
Name: Price, Length: 5397, dtype: float64

In [117]:
google // 2
google.floordiv(2)

0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
        ...
5392    166.0
5393    167.0
5394    168.0
5395    169.0
5396    169.0
Name: Price, Length: 5397, dtype: float64

## Pandas Aligns by Index Label
- We can perform mathematical operations between multiple `Series`.
- Pandas will align values by index labels, not by position.
- The resulting index will be the union (combination) of all index labels from the two `Series`.
- `NaN` is Pandas' designation for a missing value.
- Any label present in one `Series` but missing in the other produces `NaN` in the result. Pandas cannot add "unknown" to a valid numeric value.

In [118]:
revenue_ny = pd.Series([100, 200, 300], index=["Mon", "Tue", "Wed"])
revenue_ny

Mon    100
Tue    200
Wed    300
dtype: int64

In [119]:
revenue_la = pd.Series([50, 60, 70], index=["Tue", "Wed", "Thu"])
revenue_la

Tue    50
Wed    60
Thu    70
dtype: int64

- Let's find the total business revenue per day/index label.
- The `Tue` and `Wed` labels are found in both `Series.`
- The `Mon` label is only found in `revenue_ny`.
- The `Thu` label is only found in `revenue_la`.

In [120]:
revenue_ny + revenue_la
revenue_ny - revenue_la

Mon      NaN
Thu      NaN
Tue    150.0
Wed    240.0
dtype: float64

- The `add` method supports a `fill_value` parameter to provide a fallback value for missing labels.
- Pandas will assign the present label value with the `fill_value`.

In [121]:
revenue_ny.add(revenue_la, fill_value=0)

Mon    100.0
Thu     70.0
Tue    250.0
Wed    360.0
dtype: float64

## The value_counts Method
- The `value_counts` method returns the number of times that each distinct value occurs in the `Series`.

In [122]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

- Pandas returns the values in descending order (most frequent first).

In [123]:
pokemon.value_counts()

Type
Water               74
Normal              74
Grass               46
Psychic             39
Fire                36
                    ..
Rock, Electric       1
Dark, Ground         1
Dragon, Dark         1
Fairy, Fighting      1
Fighting, Dragon     1
Name: count, Length: 200, dtype: int64

- The `ascending` parameter customizes the sort order. An ascending sort places the smallest values first.

In [124]:
pokemon.value_counts(ascending=True)

Type
Steel, Ground     1
Fire, Rock        1
Rock, Dark        1
Bug, Ground       1
Bug, Ghost        1
                 ..
Fire             36
Psychic          39
Grass            46
Water            74
Normal           74
Name: count, Length: 200, dtype: int64

- The `normalize` parameter returns the relative frequencies/percentages of the values instead of the counts.
- Multiply by 100% to get the percentage.

In [125]:
pokemon.value_counts(normalize=True).mul(100).round(2)

Type
Water               7.33
Normal              7.33
Grass               4.55
Psychic             3.86
Fire                3.56
                    ...
Rock, Electric      0.10
Dark, Ground        0.10
Dragon, Dark        0.10
Fairy, Fighting     0.10
Fighting, Dragon    0.10
Name: proportion, Length: 200, dtype: float64

## The apply Method
- The `apply` method invokes a function on every `Series` value.
- The method accepts the _uninvoked_ function.

In [126]:
pokemon = pd.read_csv("pokemon.csv", usecols=["Name"]).squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

pokemon.head()

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Name, dtype: str

In [127]:
pokemon.apply(len)

0        9
1        7
2        8
3       10
4       10
        ..
1005    12
1006     8
1007     8
1008    12
1009    11
Name: Name, Length: 1010, dtype: int64

- The `apply` method supports custom functions as well.
- A pandas method for an operation will usually be faster.
- But, if you don't know the right pandas method and can write the logic in Python, `apply` is a great workaround.

In [128]:
def count_of_a(pokemon):
    return pokemon.count("a")

In [129]:
pokemon.apply(count_of_a)

0       2
1       1
2       1
3       2
4       1
       ..
1005    2
1006    1
1007    1
1008    2
1009    1
Name: Name, Length: 1010, dtype: int64

## The map Method
- The `map` method associates or connects each `Series` value to another value.
- We can pass the method a dictionary or a `Series`. Both types connect keys to values.
- The `map` method uses our argument to connect or bridge together the values.

In [130]:
pokemon = pd.read_csv("pokemon.csv", index_col="Name").squeeze("columns")
google = pd.read_csv("google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

pokemon.head()

Name
Bulbasaur     Grass, Poison
Ivysaur       Grass, Poison
Venusaur      Grass, Poison
Charmander             Fire
Charmeleon             Fire
Name: Type, dtype: str

- Let's define a dictionary mapping types to attack powers.

In [131]:
attack_powers = {
    "Grass": 10,
    "Fire": 15,
    "Water": 18,
    "Fairy, Fighting": 20,
    "Grass, Psychic": 50,
}

- Pandas will map/connect each `Series` index label to the complementary dictionary value by matching the key.

In [132]:
pokemon.map(attack_powers)

Name
Bulbasaur        NaN
Ivysaur          NaN
Venusaur         NaN
Charmander      15.0
Charmeleon      15.0
                ...
Iron Valiant    20.0
Koraidon         NaN
Miraidon         NaN
Walking Wake     NaN
Iron Leaves     50.0
Name: Type, Length: 1010, dtype: float64

In [133]:
attack_powers_series = pd.Series(attack_powers)
attack_powers_series

Grass              10
Fire               15
Water              18
Fairy, Fighting    20
Grass, Psychic     50
dtype: int64

- The `map` method also accepts another `Series` as an argument.
- Pandas will map the index labels from `pokemon` to the index labels in `attack_powers_series`.
- It will match the corresponding attack power value for each Pokemon.

In [134]:
pokemon.map(attack_powers_series)

Name
Bulbasaur        NaN
Ivysaur          NaN
Venusaur         NaN
Charmander      15.0
Charmeleon      15.0
                ...
Iron Valiant    20.0
Koraidon         NaN
Miraidon         NaN
Walking Wake     NaN
Iron Leaves     50.0
Name: Type, Length: 1010, dtype: float64